### ISSUE TITLE
allow for redirects to be overridden

### ISSUE THREAD

**Issue by airtonix** [awesto/django-shop#129]
I'm using djangoshop inside djangocms, via a cmsplugin, cmsapp and cmsmenu.

now the problem is that because shop.urls are no longer in my projects url conf (and instead handled by the menu and cmsapp), redirects in the CartDetails and CartItemDetails (or anywhere else you hardcode redirect urlconf names) fail to resolve since my shop application has it's urls namespaced.

By allowing CartDetails.as_view to accept a kwarg like success_redirect='theshop:cart', we can make using djangoshop as a cmsplugin easier.

I do want to use namespaces in my urlconf and If I am missing an obvious way to override this without modifying the code, let me know.

**Comment by jrief** [comment]
Closed. Please check version 0.9.
The Cart now is handled by a CMS page.
