### ISSUE TITLE
Shop should clean up after itself

### ISSUE THREAD

**Issue by piquadrat** [awesto/django-shop#147]
During normal usage, the shop creates instances of different models that are not used anymore at a later state. This should be documented, and methods to clean up these orphaned instances should be provided.

A (quite possibly not complete) list of such "garbage"

 * the ``Cart`` inclusion tag ``get_or_create``s a cart every time it is accessed, e.g. when Google crawles the site or somobody's just (literally) browsing *.
 * the ``CheckoutSelectionView`` creates an ``Order`` instance. If the user abandons the checkout process somewhere before reaching the ``ThankYouView``, this instance can be deleted after some time.
 * similarly, the ``CheckoutSelectionView`` creates ``Address`` instances which, at least for anonymous users, have no relation with other models, which basically makes them garbage after being serialized into the ``Order`` instance.

It's probably not a good idea to just delete this "garbage", since it may very well be perceived as valuable data, depending on the scenario. Instead, we should document these cases, and perhaps provide exemplary management commands and/or celery ``PeriodicTask``s to clean them up.

* in the case of the ``Cart`` inclusion tag, it would perhaps make sense to create the cart lazily when the first item is added to it. Different issue, though.

**Comment by jrief** [comment]
Closed. Please check version 0.9. Might be solved using the deferred pattern.
