### ISSUE TITLE
multiple address models break unique related_name constraint

### ISSUE THREAD

**Issue by Lacrymology** [awesto/django-shop#149]
I've ran into this bug while trying to run tests (http://stackoverflow.com/questions/10058277/django-test-fails-when-creating-test-database/) and a user of one of my plugins has ran into it when running my migrations: https://github.com/Lacrymology/django-shop-area-tax/issues/1

The issue seems to be the existence of two models with `ForeignKey(User, related_name="[shipping|billing]_address"..)`, i.e.: your own user-defined models and `shop.addressmodel.Address`.

Even if you don't add `shop.addressmodel` to your user models, the tests import them to use them, and then conflict arises, in the case of the bug the other user is reporting,  I'm not sure where the import's coming from.

But it has lead me to think that my own app will have the same problem, if a user wants to use the l10n app, but wants to provide their own Address model. I think I'll have to move it out of my app's models.py file, that'd do the trick, wouldn't it?

**Comment by jrief** [comment]
Closed. Please check version 0.9. Please look at the docs about deferred models.
