### ISSUE TITLE
Fail when using custom User model

### ISSUE THREAD

**Issue by atheiste** [awesto/django-shop#192]
Should use `from django.contrib.auth import get_user_model` if available.

I think that is enough to replace models\_bases/\_\_init__.py:4
for `from django.contrib import auth` and then add somewhere

    if hasattr(auth, "get_user_model"):
        User = auth.get_user_model()
    else:
        from auth.models import User

I'm not sure if it is pretty enough.

**Comment by jrief** [comment]
Closed. Please check version 0.9.
