### ISSUE TITLE
Specifying a custom address model raises ImproperlyConfigured Exception

### ISSUE THREAD

**Issue by toytonic** [awesto/django-shop#205]
Hello there,

When trying to specify a custom address model, I get the following exception:

File ".../src/django-shop/shop/util/loader.py", line 61, in load_class
    raise exceptions.ImproperlyConfigured(txt)
django.core.exceptions.ImproperlyConfigured: Backend module "wineshop.models" does not define a "ShopAddress" class.

I already had a read through previous issues and read about problems with circular dependencies when specifying a custom ShoppingCart. As I am still a beginner in django and python I cannot judge if the issues are related or not.

FYI: My AddressModel does not inherit from any django-shop base class and is definitely there where the setting points to.

SHOP_ADDRESS_MODEL = 'wineshop.models.ShopAddress'

Thanks in advance for your help!

**Comment by jrief** [comment]
Closed. Please check version 0.9.
