### ISSUE TITLE
Updating cart does not refresh quantity

### ISSUE THREAD

**Issue by kiowa** [awesto/django-shop#251]
If you update the quantity of a cart item by using a POST to the view "cart_update" the item is updated fine in the database, but the subsequent GET request to the "cart_update" view still displays the old values. You need to reload the page to get the new values.

If you comment out line 170 in cart.py it will work, but then you won't be redirected away from the POST-page.

I'm suspecting something is cached in shop/models_bases/__init__.py in the update() function at line 194.

**Comment by jrief** [comment]
Closed. Please check version 0.9.
