### ISSUE TITLE
django-shop is not python3 compatible

### ISSUE THREAD

**Issue by atheiste** [awesto/django-shop#262]
I'm trying to fix this in my branch python3. I got rid of classy-tags since they are obsolete and not ported to python3. All other libraries are already ported.

Then I made necessary changes to the source code and raised minimum django version to 1.5.1.

Now all tests (except one under python3 - the circular import is somehow not circular there) are passing under both versions. But it needs far more testing.

**Comment by jrief** [comment]
Closed. Please check version 0.9.
