### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by rollokb** [awesto/django-shop#288]
This would be nice to have. What would be needed to port this?

**Comment by jrief** [comment]
Please don't invest any time into the current django-shop implementation.
Quite soon there will be a new, and much better version of it.
Have a preview [here](https://github.com/jrief/django-shop), but please note that most docs are still outdated.

**Comment by jrief** [comment]
Closing because of version 0.9

**Comment by sirex** [comment]
Is Python 3 support was added in 0.9 version?
