### ISSUE TITLE
Just released djangoSHOP version 0.9.0rc1

### ISSUE THREAD

**Issue by jrief** [awesto/django-shop#298]
Whoever intends to build a webshop in the near future, please check this out:
https://github.com/awesto/django-shop

For me its specially important to ask for help about a topic no interpreter can test for me:

Is the documentation understandable?

**Comment by mankoell** [comment]
Wow, great work @jrief!

Shouldn't there be any links to existing payment providers? If I wouldn't have visited your profile, I would never know about [awesto/djangoshop-stripe](https://github.com/awesto/djangoshop-stripe) or [awesto/djangoshop-paypal](https://github.com/awesto/djangoshop-paypal).

The docs mention the use of django CMS, so am I right assuming you can't stick with vanilla django then?

**Comment by jrief** [comment]
> Shouldn't there be any links to existing payment providers?

Yes, thanks for reminding me

Currently we are working with Django-1.8.8 and djangoCMS-3.2.1. Whenever CMS is ready for Django-1.9, we will switch.

**Comment by Iv** [comment]
Any readme about how to migrate from django-shop 0.2 ?

**Comment by rfleschenberg** [comment]
@Iv: sorry for the late reply, we missed your question. Unfortunately there is no supported migration path from 0.2. Too much has changed. We recommend setting up a completely new project and writing a customized export / import for your existing data.

**Comment by jrief** [comment]
You can reuse your product models and you probably can reuse your cart modifiers (with some adoption). That would be the a feasible migration path.

Even with 0.2, there often are so many custom made changes to the merchant's implementation, that without seeing the code, its impossible to write a fully working receipt.
