### ISSUE TITLE
[Question] Polish translation

### ISSUE THREAD

**Issue by maltitco** [awesto/django-shop#301]
How can I join the team for the Polish translation?

**Comment by jrief** [comment]
Gerät. Yes please go ahead and create a PR
Later on wenn can proceed with transiflex
Am 06.02.2016 09:02 schrieb "maltitco" <notifications@github.com>:

**Comment by rfleschenberg** [comment]
I am closing this. @maltitco, translations are very welcome! If you need any assistance, please open a new issue or contact us directly.
