### ISSUE TITLE
Tutorial link dead

### ISSUE THREAD

**Issue by farridav** [awesto/django-shop#303]
Hi,

I was looking for a tutorial on Django shop, and found this high in search results.. http://django-shop.readthedocs.org/en/latest/tutorial.html

Seems the link is dead, any chance you can fix it for me and others wishing to run through a tutorial, perhaps a 301 to http://django-shop.readthedocs.org/en/latest/tutorial/intro.html

cheers

**Comment by jrief** [comment]
thanks for reporting, will have a look

in the meantime, please check the docs folder

**Comment by agalitsyn** [comment]
also http://www.django-shop.org/ is 404

**Comment by jrief** [comment]
This is fixed now.
