### ISSUE TITLE
Reusable apps shouldn't swap the user model

### ISSUE THREAD

**Issue by rfleschenberg** [awesto/django-shop#319]
_From @febsn on September 3, 2015 13:48_

At the moment, django-shop requires swapping in a customized user model. This is not recommended for reusable apps (see https://docs.djangoproject.com/en/dev/topics/auth/customizing/#extending-user).

I suggest creating a separate Customer model that carries all shop-specific data with a nullable OneToOne relationship to the user model. I'll write some tests to demonstrate the functionality and for discussion.

First and foremost: Should I design this for the current deferred model architecture, or already switch to django-swappable models? What are your thoughts?

_Copied from original issue: jrief/django-shop#11_

**Comment by rfleschenberg** [comment]
I believe that requiring a custom user model is fine, as long as we do not require a specific *implementation*. IIUC, we only require a user model that has a certain interface. Maybe this should be documented better. However, I am closing this issue for now. We can open a new one if this becomes a problem again.

**Comment by jrief** [comment]
@febsn proposal has already been implemented with one litte difference: Its a non-nullable 1:1-FK from the Customer to the User. Having a non-nullable key allowed me to keep the programming logic simpler.
