### ISSUE TITLE
Differences with Django Polymorphic?

### ISSUE THREAD

**Issue by rfleschenberg** [awesto/django-shop#320]
_From @cyberjoac on February 3, 2015 19:51_

I'm trying to understand the difference between django-polymorphic and DeferredForeignKey?
From my understanding, you refactored the code using DeferredForeignKey, DeferredOneToOneField etc..., while previously it was using django-polymorphic?
It seems conceptually similar to me, and I'd be happy to understand it a bit better...

What are the pros and cons of each approach?

Thanks.

_Copied from original issue: jrief/django-shop#3_

**Comment by rfleschenberg** [comment]
_From @jrief on February 2, 2016 22:55_

django-shop uses django-polymorphic in combination with deferred foreign keys. Its not a question what is better. The deferred pattern is explained in here: http://django-shop.readthedocs.org/en/latest/reference/deferred-models.html

**Comment by jrief** [comment]
The deferred pattern allows us to create lazy foreign keys. With lazy, I mean foreign keys which yet do not know anything about the model they are pointing to. [Django Swappable](https://github.com/wq/django-swappable-models) aims for a similar functionality, but when I wrote it that app was not available yet, and in my opinion it makes the models in the merchant's project, look and feel more naturally.

**Comment by rfleschenberg** [comment]
Closing. @cyberjoac, if you still have any questions, please feel free to contact us or open a new issue. Thanks!
