### ISSUE TITLE
ImproperlyConfigured error when defining a new product

### ISSUE THREAD

**Issue by JonathanBergers** [awesto/django-shop#323]
Hi there.
Just created an example app and trying to define a new product in the smartcard.py file, but when i start the server i get the following error:

> shop/models/product.py", line 64, in __new__
>     .format(name, Model, baseclass._materialized_model))
> django.core.exceptions.ImproperlyConfigured: Abstract base class TestProduct has already been associated with a model <class 'myshop.models.simple.smartcard.TestProduct'>, which is different or not a submodel of <class 'myshop.models.simple.smartcard.SmartCard'>.

Is it only possible to define one product that extends baseproduct for the shop?
How do i create a new product for my shop.. ?
My test product class is almost the same as the smartcart but with less attributes.

```

@python_2_unicode_compatible
class TestProduct(BaseProduct):
    # common product fields
    product_name = models.CharField(max_length=255, verbose_name=_("Product Name"))
    slug = models.SlugField(verbose_name=_("Slug"))
    unit_price = MoneyField(_("Unit price"), decimal_places=3,
        help_text=_("Net price for this product"))
    description = HTMLField(verbose_name=_("Description"),
                            help_text=_("Description for the list view of products."))

    # product properties
    manufacturer = models.ForeignKey(Manufacturer, verbose_name=_("Manufacturer"))
    # some attr
    color = ['red', 'green']
    product_code = models.CharField(_("Product code"), max_length=255, unique=True)
   
    # controlling the catalog
    order = models.PositiveIntegerField(verbose_name=_("Sort by"), db_index=True)
    cms_pages = models.ManyToManyField('cms.Page', through=ProductPage,
        help_text=_("Choose list view this product shall appear on."))
    images = models.ManyToManyField('filer.Image', through=ProductImage)

    objects = BaseProductManager()

    # filter expression used to search for a product item using the Select2 widget
    lookup_fields = ('product_code__startswith', 'product_name__icontains',)

    class Meta:
        verbose_name = _("Vibra")
        verbose_name_plural = _("Vibras")
        ordering = ('order',)

    def __str__(self):
        return self.product_name

    @property
    def sample_image(self):
        return self.images.first()

    def get_price(self, request):
        return self.unit_price

    def get_absolute_url(self):
        # sorting by highest level, so that the canonical URL associates with the
        # most generic category
        cms_page = self.cms_pages.order_by('depth').last()
        if cms_page is None:
            return urljoin('category-not-assigned', self.slug)
        return urljoin(cms_page.get_absolute_url(), self.slug)
```

Any help appreciated!

**Comment by jrief** [comment]
Is this the "simple" demo? The "polymorphic" demo explains in detail how to create different types of products, which derive from one base class, ie. ``Product``.

BTW, please retry with https://github.com/jrief/django-shop , which soon will be merged with the official (this!) version. There is also a runnable docker container now.

**Comment by JonathanBergers** [comment]
@jrief Thx for answering, yes, this is the simple demo.
In the polymorphic demo one uses one 'smartphone model' model and extends this using a foreign key.
Is it only possible to extend the baseproduct class with 1 subclass? or can i use multiple subclasses of the base class ?  looking at the error i think the first one is true.. if i want to create a different product than the smartcart, do i have to use a foreign key to the base product?

**Comment by jrief** [comment]
No, this works automatically. Check the inheritance tree from ``SmartPhone``, ``SmartCard`` or ``Commodity`` to ``Product``.
Its also explained in django-polymorphic

**Comment by rfleschenberg** [comment]
@JonathanBergers Is this still an issue for you?

**Comment by rfleschenberg** [comment]
Closing. @JonathanBergers, please open a new issue if you are still having problems. Thanks!
