### ISSUE TITLE
Environment DJANGO_SHOP_TUTORIAL has an invalid value

### ISSUE THREAD

**Issue by insta-code1** [awesto/django-shop#347]
Hi there!

I would like to run the Simple Product Demo, however I get an error when I run the following:

(shoptutorial)$ cd example
(shoptutorial)$ export DJANGO_SHOP_TUTORIAL=simple DJANGO_DEBUG=1
(shoptutorial)$ ./manage.py migrate     # this is where I get the error of:

File "D:\Tutorial\django-shop\example\myshop\settings.py", line 23, in <module>
    raise ImproperlyConfigured("Environment DJANGO_SHOP_TUTORIAL has an invalid value `{}`".format(SHOP_TUTORIAL))
django.core.exceptions.ImproperlyConfigured: Environment DJANGO_SHOP_TUTORIAL has an invalid value `simple DJANGO_DEBUG=1`

Do you have have any suggestions? 

Thanks!

**Comment by jrief** [comment]
This has been refactored yesterday and now is named ``smartcard``, ``i18n_smartcard`` and ``polymorphic``. On readthedocs these changes are not visible yet. So please try with ``smartcard``.

**Comment by insta-code1** [comment]
I still get the same error with export DJANGO_SHOP_TUTORIAL=smartcard DJANGO_DEBUG=1

raised from the setting file: on line 22

if SHOP_TUTORIAL not in ('simple', 'i18n', 'polymorphic',):
    raise ImproperlyConfigured("Environment DJANGO_SHOP_TUTORIAL has an invalid value `{}`".format(SHOP_TUTORIAL))

could it be because 'smartcard' is not listed in the array? 

I'll go forward adding pages to the cms.

Cheers!

**Comment by jrief** [comment]
Sorry there is some kind of commit mismatch.
For the moment, please use my development version from https://github.com/jrief/django-shop
This will all be fixed for version 0.9.2. There, another two product examples will be added.

**Comment by insta-code1** [comment]
Thanks man!

**Comment by rfleschenberg** [comment]
I cannot reproduce this with the current Awesto master. Looking at the error message, I think this is actually a Windows problem: **``has an invalid value simple DJANGO_DEBUG=1``**. Though I wonder how you managed to cause this error, because AFAIK ``export`` does not exist on Windows?

Anyway, I do not use WIndows, so I am not sure how to set environment variables there. Maybe you have to split this up into two commands. Something like this?

```
set DJANGO_SHOP_TUTORIAL=simple 
set DJANGO_DEBUG=1
```

**Comment by MacLake** [comment]
Could you please mention this in the documentation, as it is a bin cumbersome to ggogle for all the error messages. Anyway, thanks for this nice shop system, which seem to fit our needs from what I saw.
