### ISSUE TITLE
Wrong variable name for csrf token

### ISSUE THREAD

**Issue by rubengrill** [awesto/django-shop#353]
In the example project `{% csrf_value %}` is used.
Shouldn't that be `csrf_token` and a variable instead of a block?
https://github.com/awesto/django-shop/blob/4651abaf7df4e764fd820b9949eb0e1d8368f56c/example/myshop/templates/myshop/pages/base.html#L51

```
{{ csrf_token }}
```

**Comment by jrief** [comment]
AFAIK csrf_token adds a hidden input field, but here we need a value.

**Comment by rubengrill** [comment]
The csrf_token can both be used as a template tag (input) or as a variable (value only, set by csrf context processor).
https://docs.djangoproject.com/en/1.8/ref/csrf/#other-template-engines

**Comment by jrief** [comment]
Thanks for pointing out. Actually, I use ``{% csrf_value %}`` from the django-angular project, which was added before Django added that feature.

**Comment by rubengrill** [comment]
Ah, thats where this tag comes from. I did not install it and this tag raised an error, thats why I reported it.
This issue can be closed then.
