### ISSUE TITLE
Add CategoryFilter

### ISSUE THREAD

**Issue by vivazzi** [awesto/django-shop#361]
Hi, devs! I want to suggest CategoryFilter for admin. I found it useful for my project. And maybe it will useful for others:
```
class CategoryFilter(admin.SimpleListFilter):
    title = _('Category')
    parameter_name = 'category'

    def lookups(self, request, model_admin):
        limit_choices_to = {'publisher_is_draft': False, 'application_urls': 'ProductsListApp'}
        queryset = Page.objects.filter(**limit_choices_to)
        return [(page.id, page.get_title()) for page in queryset]

    def queryset(self, request, queryset):
        if self.value():
            return queryset.filter(cms_pages__id=self.value())


@admin.register(Product)
class ProductAdmin(SortableAdminMixin, CMSPageAsCategoryMixin, models.ModelAdmin):
    list_filter = (CategoryFilter, )
```

This code may be put to shop/admin/product.py

P. S. The title CategoryFilter may be incorrect title for universial shop. I don't know how should call more correct title..

**Comment by jrief** [comment]
Thanks
How about naming it something like CMSPageFilter?
In my opinion it fits better to the terminology

**Comment by vivazzi** [comment]
I am agree. Product has field "cms_pages" then name CMSPageFilter is more fit for filter.

**Comment by jrief** [comment]
Thanks for the hint. A ``CMSPageFilter `` will be added in version 0.9.2.
