### ISSUE TITLE
Use 'active' in sitemap for product

### ISSUE THREAD

**Issue by vivazzi** [awesto/django-shop#362]
I think it need add the filter by 'active' field in sitemap (django-shop/shop/views/sitemap.py), using something manager:
```
    def items(self):
        return ProductModel.objects.active()
```
Although, each site can have own logic for active. If I correct understand, 'get_availability' in BaseProduct can used in manager with method active() (like as above). I hope you develop my idea

**Comment by jrief** [comment]
The intention of ``active`` is to set it to false instead of removing the the product. This is required for SEO purpose, so that products are still reachable through the search engine, even if the have been removed from the catalog.

**Comment by vivazzi** [comment]
If the have been removed from the catalog, then how product is displayed by url? I think we need show 404 error page for this case, need not we?

**Comment by jrief** [comment]
That would be the logical behavior, but the SEO typically recommends to mark that product as gone.
Google for "SEO considerations for discontinued products in ecommerce" and/or listen to Matt Cutts.
Probably the best is to use kind of meta-tag.

**Comment by vivazzi** [comment]
Thank you for material about SEO. For different cases we try to display appropriate 404 page. For example, for product is 'Sorry, but product is saled' or for article is 'Article is removed' and so on. Nevertheless I'm agree with you about SEO.

**Comment by jrief** [comment]
Good point. So want you can do is to replace the url-config for your products as

myshop/urls/product.py:

```
urlpatterns = [
    ...
    url(r'^(?P<slug>[\w-]+)/?$', ProductRetrieveView.as_view(
        serializer_class=ProductDetailSerializer,
        limit_choices_to=Q(active=True),
    )),
    ...
```

this would raise a NotFound exception for inactive products. Disclaimer: never tested.

**Comment by vivazzi** [comment]
Thanks for code! I will think about how is better. But now I think this issue may be closed.
