### ISSUE TITLE
Add more examples of using of adding products in cart

### ISSUE THREAD

**Issue by vivazzi** [awesto/django-shop#363]
I need more examples of work with cart and REST framework to DjangoShop docs. I don't use angular and I need extend the logic of adding products in cart.

I have cloth shop. One product has one or more sizes and colors. 

Firstly, I need store more atributes for CartItem. I extended default CartItem:
```
class CartItem(cart.BaseCartItem):
    quantity = models.IntegerField(validators=[MinValueValidator(0)])
    color = models.CharField('Color', null=True, blank=True)
    size = models.CharField('Size', max_length=5, null=True, blank=True)
```
In product-detail.html I use next code to add product in cart:
```
$(function(){
    var d = {
        'quantity': 1,
        'unit_price': '120',
        'subtotal': '120',
        'product': 1,
        'color': 'white',
        'size': 'XL'
    };
    $('.buy').click(function(){
        $.post('{% url 'shop:cart-list' %}', d, function() {
            alert('product is added to cart')
        });
    });
});
```
But color and size don't save in my CartItem.

Secondly, I want see my cart as like:
```
name           color   size   quantity
product_1   white   XL   1
product_1   black   S   2
``` 
product_1 has same id. Now if I add product_1 product in cart then I get:
```
name           color   size   quantity
product_1   white   XL   3
```
How I add product to cart separately if size or color different?

Please, help me. I think I need customize serializer but I can't it bacause I get errors.

I think DjangoShop docs need more examples to developers could be understand how they can extend their shop logic.

**Comment by jrief** [comment]
First of all, I would store product variations inside the ``extra`` field, otherwise you also must redefine your own ``OrderItem``. But if you want to do it as explicit fields, then you have to create your own ``AddToCartSerializer`` for the additional fields ``color `` and ``size``. Have a look at how ``AddSmartCardToCartSerializer`` is implemented in ``example/myshop/serializers.py``.

For adding product variants, override the method ``is_in_cart(...)``. This should return the cart item, if the product to add is considered the same, or None, if it should be added. This is documented though.

You should also override the method ``get_instance(...)`` so that you can deliver the initial data, say size and color choices, to the product's detail view which renders the AddToCart form.

**Comment by vivazzi** [comment]
Thank you very much! I try to realized your hints and will say about my result. Also I try to improve using django shop in russian community through my blog. I think it system is the most flexly and powerful. I like its concepts. Thank you for django shop!

**Comment by vivazzi** [comment]
Thank you, Jacob for your help. I have finished my aim.

**Comment by nichosninos** [comment]
hello vivazzi, I am also trying to implement a clothline cart which has color ans size but size and color are not being saved to the database. do you mind sharing your  solution. Thank you

**Comment by nichosninos** [comment]
You guys are just so good in this. I have tried reading about **AddToCartSerializer** and tried editing many that have been implemented but all in vain. it still isn't getting me those elements in the checkout process. I am currently trying to edit [shopping cart](https://github.com/muvatech/Shopping-Cart-Using-Django-2.0-and-Python-3.6) but it is way to complex to add those elements (color and size) for me. If you can look through and maybe suggest the edits I have to implement or suggest another option, that will be highly appreciated. Thanks

**Comment by vivazzi** [comment]
@nichosninos When I use django-shop firstly, it was difficult for me. Because django-shop requires stack technologies: angular, serializers and so on. I recommend to learn each package that there are in requirements. Because I have understood how it works when I understood each library.
Personally, I can't help with django-shop, I can't tell more details, since I already haven't used django-shop for about one years.. It is need some time to remember django-shop.

**Comment by nichosninos** [comment]
Thanks a lot. I took your word and now I'm learning it from scratch. I thought there could be a shortcut but the shortcut is to learn. Thank you
