### ISSUE TITLE
CatalogLinkForm has problems

### ISSUE THREAD

**Issue by rfleschenberg** [awesto/django-shop#377]
There are two problems with `CatalogLinkForm`: 

1. When linking to a product, the select widget for the product is much too narrow, you cannot read the text.

2. The widget only allows to select from the first 10 products.

**Comment by jrief** [comment]
Problem 1 has been solved already, please let me search for the fix. Presumably in another branch.

**Comment by rfleschenberg** [comment]
Maybe the problem with 1. is just an outdated docker demo. I am planning to look into this anyway. 2. was probably my bad, I didn't RTFM.
