### ISSUE TITLE
Support for Django 1.10

### ISSUE THREAD

**Issue by khchine5** [awesto/django-shop#386]
Hi all,
I have tested django-shop with django 1.10 and all tests pass as shown on [travis](https://travis-ci.org/khchine5/django-shop). Could I make a PR to add support for django 1.10 ?

**Comment by rfleschenberg** [comment]
Hi,

Yes, please go ahead with the PR!

Unfortunately, we must admit that our tests are somewhat of a weak spot right now, so the fact that they pass with Django 1.10 doesn't mean that much :) Maybe this is a good opportunity to improve our test suite.

**Comment by khchine5** [comment]
Yes, you are right.
I'll contribute by adding some useful tests.

**Comment by rfleschenberg** [comment]
I fixed travis so that it actually runs the tests on Django 1.10 now :)

**Comment by amadornimbis** [comment]
django-shop seems to not be compatible with djangocms-cascade v0.12.0. I get the following error in my project, which seems to be due to [this line](https://github.com/awesto/django-shop/blob/master/shop/cascade/settings.py#L5):
```
Traceback (most recent call last):
  File "manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/eric/.virtualenvs/nimbis/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/eric/.virtualenvs/nimbis/lib/python2.7/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.configure()
  File "/Users/eric/.virtualenvs/nimbis/lib/python2.7/site-packages/django/conf/__init__.py", line 65, in configure
    raise RuntimeError('Settings already configured.')
RuntimeError: Settings already configured.

, which is a blocker for Django 1.10 support. Django 1.9 is only has extended support for a couple of more weeks

**Comment by jrief** [comment]
@amadornimbis 
Django-SHOP 0.10 run with Django-1.10.x and django-CMS-3.4.2
