### ISSUE TITLE
npm install fails: peerinvalid

### ISSUE THREAD

**Issue by MacLake** [awesto/django-shop#393]
Hello,

I got stuck during installing Django Shop: When it comes to „npm install“ i get
> $ npm install
> npm ERR! peerinvalid The package angular does not satisfy its siblings' peerDependencies requirements!
> npm ERR! peerinvalid Peer angular-stripe@4.2.12 wants angular@>=1.3 <=1.5
> 
> npm ERR! System Linux 3.16.0-4-amd64
> npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
> npm ERR! cwd /home/jens/django/Tutorial/django-shop
> npm ERR! node -v v0.10.29
> npm ERR! npm -v 1.4.21
> npm ERR! code EPEERINVALID
> npm ERR! 
> npm ERR! Additional logging details can be found in:
> npm ERR!     /home/jens/django/Tutorial/django-shop/npm-debug.log
> npm ERR! not ok code 0

on my Debian Jessie with Python 3.4.2. Any hints how I resolve this would be appreciated.

**Comment by jrief** [comment]
you probably have an outdated version of node.js / nmp
Please check their support for solving this problem, since this is unrelated to django-shop
Please close this issue, if you were able to solve it

**Comment by MacLake** [comment]
Thanks, [updating node.js/npm](https://github.com/nodesource/distributions) did help indeed.

I agree that it’s not an issue within django-shop, but anyway, mentioning a minimum version for node.js/npm would help people who are much not into npm (yet) like me, especially because Debian stable is quite widespread as a server system.
