### ISSUE TITLE
composition + deferred models [MRO]

### ISSUE THREAD

**Issue by jab3z** [awesto/django-shop#396]
On class composition between any other abstract models classes and shop deferred models, the deferred has to be the most right ancestor otherwise the deferred fields will not materialized.

I'm not sure if this is a bug. I suggest to add this to documentation.

`class FooModel(BarModel, AnyShopDeferredModel):` is good
`class FooModel(AnyShopDeferredModel, BarModel):` is not good.

**Comment by jrief** [comment]
I never intended to allow model mixins, therefore your code is not a use-case I expected.
Anyway, I assume that if ``BarModel`` is abstract too, then your code is correct. I'll add a note to the docs.

**Comment by jab3z** [comment]
Yes, it's abstract. 👍
