### ISSUE TITLE
BaseOrder JSONfields default uses mutable dicts

### ISSUE THREAD

**Issue by simonfloris** [awesto/django-shop#397]
https://docs.djangoproject.com/en/1.9/ref/contrib/postgres/fields/#jsonfield

I'm not 100% sure if this applies to to jsonfield.JSONField  but I think this should be changed
from default={} 
to 
default=dict for 
BaseOder.extra and BaseOrder.stored_request

**Comment by jrief** [comment]
Hi @simonfloris 
thanks for pointing this out.

Currently djangoSHOP uses https://pypi.python.org/pypi/django-jsonfield which is portable across databases. The JSONField you refer to, is specific to Postgres only, hence not portable.

I might create a wrapper which uses whatever is more suitable to the used database. I just reread the docs from ``jsonfield.JSONField`` and it states:

```
If no default is provided, and null=True is not passed in to the field constructor, then a default of {} will be used.
```

Therefore I removed all occurrences of ``default={}``.

**Comment by jrief** [comment]
Feel free to implement #398
