### ISSUE TITLE
Create JSONField which wraps implementation of django.contrib.postgres and jsonfield

### ISSUE THREAD

**Issue by jrief** [awesto/django-shop#398]
**djangoSHOP** currently uses the ``JSONField`` from https://pypi.python.org/pypi/django-jsonfield which is portable and the only available choice on Django-1.8.

Now that Django ships with its own ``JSONField``, we should use that. Unfortunately it is specific to Postgres only, hence we need a mechanism which wraps the ``JSONField`` and only uses the Postgres specific one, if we know for sure, that the database runs on Postgres, otherwise it uses the other one.

Since all occurrences of ``JSONField`` have  ``default=dict``, this default shall be integrated into that wrapping field. This field shall be implemented in ``shop.models.fields.py``.

**Comment by rfleschenberg** [comment]
PR #399 got merged in, closing the issue.
