### ISSUE TITLE
Not able to load demo data from fixture

### ISSUE THREAD

**Issue by gtoffoli** [awesto/django-shop#402]
I plan to develop a relatively simple e-commerce application on Ubuntu, but, as I did in many other cases, I'm starting the development on my Windows notebook (Windows 10, Python 3.5, Django 1.9.7).
To get acquainted with django-shop (and with django-cms), I'm willing to run its demos from the example project.

Following the documentation, in steps 1.1 to 1.3, I found only some minor problems: had to remove the ^ character from package.json file and to install with pip a few missing packages.
Then I tried to run the demos of the example project, starting from step 2.2.
I found that, in the online doc (django-shop.readthedocs.io/en/latest) and in the PDF version of the documentation, the demos and their names are not aligned with the 3 fixtures actually available in the example/fixtures folder and with the 5 SHOP_TUTORIAL options in the example/myshop settings module.
But even for a demo such as i18n_smartcard, which is consistently mentioned in the documentation and in the software, I wasn't able to populate the database with the fixture data.
Here are the first lines of the traceback, in some context:
```
(django19) C:\django19\Tutorial\django-shop\example>SET DJANGO_DEBUG=1
(django19) C:\django19\Tutorial\django-shop\example>SET DJANGO_SHOP_TUTORIAL=i18n_smartcard
(django19) C:\django19\Tutorial\django-shop\example>python manage.py migrate
... (ok)
(django19) C:\django19\Tutorial\django-shop\example>python manage.py loaddata fixtures/myshop-i18n_smartcard.json
Traceback (most recent call last):
  File "C:\django19\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\django19\lib\site-packages\django\db\backends\sqlite3\base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: cms_cmsplugin.position
...
```

**Comment by jrief** [comment]
Hi Giovanni,
it might be that the current version on GitHub evolved faster than the fixture you are using. Your problem seems to be related to djangocms-cascade, which evolved a lot in the last month.

If you agree, I can send you my current demo database dump (SQLite) and a zip-files with the used media files. This should help you to get a demo up and running quickly.

**Comment by gtoffoli** [comment]
Hi Jacob,
yes, I would be very glad to receive your database dump and media files.
Thank you very much for your fast reply and your willingness!

**Comment by rfleschenberg** [comment]
Can you tell us which packages were missing? I would like to add them to the requirements files.

**Comment by gtoffoli** [comment]
I thought that 6 packages were missing since, after installing from the requirements file, I got 6 import errors, and overcome them by installing, with individual pip commands, the apparently missing packages. But I cannot understand why this happened, since

- in fact all package names are present in the requirements file
- I kept the console output of the pip install -r command, and it seems that the required packages were found and installed without problems.

Anyway, this is the sequence of commands that I issued:

> (django19) C:\django19\Tutorial\django-shop>pip install -r requirements/py3/common.txt
> ...
> (django19) C:\django19\Tutorial\django-shop\example>python manage.py shell
> ...
> ImportError: No module named 'djangocms_text_ckeditor'
> ...
> (django19) C:\django19>pip install djangocms-text-ckeditor
> ...
> (django19) C:\django19\Tutorial\django-shop\example>python manage.py shell
> ...
> ImportError: No module named 'cmsplugin_cascade'
> ...
> (django19) C:\django19>pip install djangocms-cascade
> ...
> (django19) C:\django19\Tutorial\django-shop\example>python manage.py shell
> ...
> ImportError: No module named 'cms_bootstrap3'
> ...
> (django19) C:\django19>pip install djangocms-bootstrap3
> ...
> (django19) C:\django19\Tutorial\django-shop\example>python manage.py shell
> ...
> ImportError: No module named 'haystack'
> ...
> (django19) C:\django19>pip install haystack
> ...
> (django19) C:\django19\Tutorial\django-shop\example>python manage.py shell
> ...
> ImportError: No module named 'shop_stripe'
> ...
> (django19) C:\django19>pip install djangoshop-stripe
> ...
> (django19) C:\django19\Tutorial\django-shop\example>python manage.py shell
> ...
> ImportError: No module named 'elasticsearch'
> ...
> (django19) C:\django19>pip install elasticsearch
> ...
>
