### ISSUE TITLE
Missing demo from docs

### ISSUE THREAD

**Issue by Kurdakov** [awesto/django-shop#411]
Docs mention  "have a look in the prepared demo project for the Cart and Checkout pages"

http://django-shop.readthedocs.io/en/latest/tutorial/cart-checkout.html or
https://github.com/awesto/django-shop/blob/master/docs/tutorial/cart-checkout.rst

but cannot see it anywhere - git contains only example project which lacks cart demo.

**Comment by jrief** [comment]
Good that you are mentioning this. I'm currently putting together a new demo with a new fixture.
In the meantime feel free to create your own cart and checkout pages; every form element is already available for composition.

**Comment by Kurdakov** [comment]
ok thanks for a new demo effort.

yes, code is there, just wanted to use it in specialized way 
so it will be two step process for me - first to create such something that  works, then transform that basic application 
to specialized workflow ( not based on django sms, but quite a different in house sms )

**Comment by Kurdakov** [comment]
here is a problem I have:
I try to follow a logic described here: http://django-shop.readthedocs.io/en/latest/reference/cart-checkout.html
"Sessions expire, but then the cart’s content of anonymous customers still remains in the database"

In my attempt once a visitor goes to the page with a Cart - I create a cart via

cart = CartManager.get_or_create_from_request(request) and request has a VisitorCustomer
a code for get_or_create_from_request is following:
==
def get_or_create_from_request(self, request):
        if request.customer.is_visitor():
            request.customer = CustomerModel.objects.get_or_create_from_request(request)
        cart, temp = self.get_or_create(customer=request.customer)
        return cart
==
but 
a line
        cart, temp = self.get_or_create(customer=request.customer)

raises exception due to the fact that VisitorCustomer in current code is derived from object and obviously does not have fields of BaseCustomer in BaseCart:
( in BaseCart )
customer = deferred.OneToOneField('BaseCustomer', verbose_name=_("Customer"), 
related_name='cart')

so what is not obvious from current code:

how to create Cart for visiting Customer and then how to transfer this cart to actual materialized Customer

**Comment by rfleschenberg** [comment]
If I understand correctly, we can close this.
