### ISSUE TITLE
How I change quantity without angular

### ISSUE THREAD

**Issue by vivazzi** [awesto/django-shop#412]
I'm sorry for stupid question, but I can't change quantity of product without angular.

My REST settings:
```
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'shop.rest.money.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer', 
    ),
    'DEFAULT_FILTER_BACKENDS': ('rest_framework.filters.DjangoFilterBackend',),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 20,
}
```
I try:
```
<script>
    $.ajaxSetup({
        beforeSend:function (xhr, settings) {
            if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                xhr.setRequestHeader('X-CSRFToken', '{{ csrf_token }}');
            }
        },
        cache:false
    });


$.ajax({
    url: url,
    type: 'PUT',
    data: {'product': 16,
           'quantity': 20}
}).done(function(){

    alert('ok')
});
</script>
```
I get answer:
```
{"detail":"CSRF Failed: CSRF token missing or incorrect."}
```
Athough, I set `xhr.setRequestHeader('X-CSRFToken', '{{ csrf_token }}');`

But If I run code in console:
```
http -a my_login:my_password PUT http://127.0.0.1:8000/shop/api/cart/14/ product=16 quantity=20
```
quantity is changed. 

How I can change quantiy throught $.ajax?

I wiil glad for help.

UPD: I read http://www.django-rest-framework.org/topics/ajax-csrf-cors/ and I added:
```
'DEFAULT_AUTHENTICATION_CLASSES': (
      'rest_framework.authentication.SessionAuthentication',
),
```
but I still can't resolve my task.

**Comment by jrief** [comment]
well, the Angular part of djangoSHOP also changes the quantity through AJAX. If you get the response ``"CSRF Failed: CSRF token missing or incorrect."`` then that token is probably missing. Why don't you add it always, what's the purpose of 
```
if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {...
```
?

**Comment by vivazzi** [comment]
All this code:
```
$.ajaxSetup({
        beforeSend:function (xhr, settings) {
            if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                xhr.setRequestHeader('X-CSRFToken', '{{ csrf_token }}');
            }
        },
        cache:false
    });
```
help set csrf_token for ajax. This code copy & paste from some project, maybe this code is taken from Django tutorial. Propose of `if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url)))` I can't answer.. For me `$.ajaxSetup ... ` is black box.

Nevertheless, `$.ajaxSetup ... ` works for always, but it does not wwork with rest framework if I undestand correctly

**Comment by jrief** [comment]
Did you have a look at the sent HTTP headers, using some browser dev tools?

**Comment by vivazzi** [comment]
![pic](https://cloud.githubusercontent.com/assets/11954799/18663283/70aaa384-7f50-11e6-8489-0f58d8dc26b7.png)

Screenshot shows that csrftoken is in cookie

**Comment by jrief** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/1132472/18664817/97e9418e-7f24-11e6-9923-87d5b2420578.png)

that's only half the job, you also must assure that the token is send as HTTP header
