### ISSUE TITLE
Replacement for `can_be_added_to_cart` property from version 0.2?

### ISSUE THREAD

**Issue by dinoperovic** [awesto/django-shop#415]
Returning `[(0, datetime.max)]` in `Product.get_availability()` doesn't seem to work. Product is still added to cart. I've found there is a `BaseItemSerializer.validate_product()` method that checks if product is inactive, and restricts it from being added to cart.

Is there another way to restrict a product from being added to the cart?

**Comment by jrief** [comment]
sorry, this has not been implemented yet. I just wanted to declare a future proof way to handle the availability of products over time.

**Comment by jrief** [comment]
in the meantime you can however use the ``active`` flag, if that's enough.

**Comment by dinoperovic** [comment]
Got it. Thanks.
