### ISSUE TITLE
CustomerStateField permanent validation failure

### ISSUE THREAD

**Issue by racitup** [awesto/django-shop#425]
Hi I appear to have found a bug with the CustomerStateField in django-shop c8b7f1fe0db4aa0e16c39e0ceff736a964fa7a3a

On loading the customer page in the admin interface and trying to save, I get the error below.
It doesn't matter what value I choose I still get the error.
I get this with both the example shop and the shop I am building.

Hope you can help and let me know if there's anything I can do to help! :)

![screen shot 2016-09-27 at 04 32 13](https://cloud.githubusercontent.com/assets/18157195/18859382/802abe8c-846b-11e6-8712-f882fbf435b8.png)

**Comment by jrief** [comment]
This has been fixed in the next big release, already available on my development branch at https://github.com/jrief/django-shop

**Comment by racitup** [comment]
That's great thanks!
Could you tell me when the fix might get merged into the pip project please?

**Comment by rfleschenberg** [comment]
@jrief: Is the fix already merged into master? Then we should close this issue.

@racitup: Expect a release in the upcoming week.

**Comment by racitup** [comment]
Just tested it on the example in version 0.10.2 and it is fixed. Thanks both!
