### ISSUE TITLE
setup.py required Django version should be less than 1.11

### ISSUE THREAD

**Issue by destos** [awesto/django-shop#437]
The specified Django version locks it absolutely to  the 1.10 minor release preventing you from installing security updates via pip for 1.10.

```python
'Django>=1.9,<=1.10',
```
should be changed to:
```python
'Django>=1.9,<1.11',
```

That way we can specify anything up to 1.11. Was this a mistake?  If not I don't mind making a quick PR with the fix in place.

**Comment by jrief** [comment]
sorry, it should actually be <1.10.
currently there is still an issue with a few CMS plugins and django-1.10

**Comment by jrief** [comment]
In the meanwhile I got a report that it works with django-1.10
