### ISSUE TITLE
Shopping cart issues 

### ISSUE THREAD

**Issue by maltitco** [awesto/django-shop#438]
Hi, in the case of adding the product to the basket and select purchase as a guest is’t no longer possible to register (create account). Even after the completion of the first order, while submitting another still you can submit only as a guest.

[https://vimeo.com/189136159](url)

**Comment by jrief** [comment]
Thanks for the Video, a very good tool to explain bugs.

Indeed, this is a "bug" in the setup, not in django-SHOP itself.
So, how can you prevent this?

1. On the checkout page switch into edit mode.
2. Open the DOM tree's editor for the Main Content placeholder
3. Locate Process Step 1
4. Open the "Segment else"
5. Add a plugin named "Authentication", as Rendered Form use "Register User" (this form already exists in the guest section)

One problem here is that you somehow have to communicate your customer that they get a "second chance" to register themselves.

I hope this is enough for you to fix it and thanks for pointing out.

**Comment by jrief** [comment]
Can we close this issue?

**Comment by jrief** [comment]
Closed for inactivity
