### ISSUE TITLE
Temp password is not valid in PasswordResetConfirm

### ISSUE THREAD

**Issue by dinoperovic** [awesto/django-shop#455]
When accessing the `PasswordResetConfirm` view, `PasswordResetConfirmSerializer.is_valid()` fails with the default django `AUTH_PASSWORD_VALIDATORS` setting.

> {'new_password2': [u'This password is too short. It must contain at least 8 characters.', u'This password is too common.']}

I managed to get around this by changing:
`password = 'x' * serializer_class._declared_fields['new_password1']._kwargs.get('min_length', 3)`
to:
`password = get_user_model().objects.make_random_password()`

**Comment by jrief** [comment]
could you please create a pull request
