### ISSUE TITLE
errors starting the tutorial

### ISSUE THREAD

**Issue by patl12345** [awesto/django-shop#457]
Running through the tutorial in windows/python 3.4. All goes fine until 
./manage.py migrate 
at which point I get:
ImportError: No module named 'email_auth'
This is fixed if, instead of doing 
pip install --nodeps -e
I install dependencies with
pip install -e

**Comment by jrief** [comment]
``email_auth`` is part of the django-shop package. Did add this to the Python search path?

**Comment by jrief** [comment]
Have you been able to fix it? I'd like to close this issue.

**Comment by patl12345** [comment]
Hi,
I haven't spent any more time looking at it I'm afraid, so feel free to close.
Regards,
Pat






On Fri, Nov 18, 2016 at 3:17 PM +0000, "Jacob Rief" <notifications@github.com> wrote:












Have you been able to fix it? I'd like to close this issue.

**Comment by rfleschenberg** [comment]
Closing for now, please reopen or file a new issue if needed.
