### ISSUE TITLE
How about sitemap?

### ISSUE THREAD

**Issue by vivazzi** [awesto/django-shop#478]
Sites need sitemap. In example app I found only:
```
url(r'^sitemap\.xml$', sitemap, {'sitemaps': {'cmspages': CMSSitemap}}, name='sitemap'),
```

Maybe add Sitemap for products like this:
```
class ProductSitemap(Sitemap):
    changefreq = 'monthly'
    priority = 0.5
    i18n = True

    def items(self):
        return Product.objects.filter(active=True)
```
In this code I see one problem: class `Product` may be different.

**Comment by jrief** [comment]
Yes, this for be a good addition for the sample project. Do you want to try adding it?
I'm using sitemaps for my customers e-commerce sites.

**Comment by vivazzi** [comment]
Yes, I will try!

**Comment by rfleschenberg** [comment]
One hint if you're going to implement this: Watch out for n+1 queries. This can quickly become a problem in sitemaps. `select_related` / `prefetch_related` may help.

**Comment by vivazzi** [comment]
Added PR: https://github.com/awesto/django-shop/pull/479

**Comment by vivazzi** [comment]
Maybe we'll close this issue?

**Comment by rfleschenberg** [comment]
Yup. Thanks for your contribution!
