### ISSUE TITLE
Settings should return resolved values

### ISSUE THREAD

**Issue by rubengrill** [awesto/django-shop#484]
I would like to start a PR to change how settings are read, inspired by how allauth does that (https://github.com/pennersr/django-allauth/blob/master/allauth/account/app_settings.py):

Add a new file `shop/app_settings.py`. This would allow us to import settings without having to rename the module:
```
from django.conf import settings
# from shop import settings as shop_settings
from shop import app_settings
```

In this File, create a class `AppSettings` that has properties for each setting. This property returns already the resolved value, e.g. `SHOP_CUSTOMER_SERIALIZER` currently returns a string, every module reading that property needs to import that module to use that serializer.
https://github.com/pennersr/django-allauth/blob/master/allauth/account/app_settings.py#L200

A nice way to keep the settings compliant is to replace the module by an instance of the `AppSettings`:
https://github.com/pennersr/django-allauth/blob/master/allauth/account/app_settings.py#L328

What is also an advantage next to getting resolved values:
- We avoid the trap of circular dependencies, as the evaluation of a setting is only done when the setting is accessed, not when the shop settings are imported the first time.
- We allow that a project can test against different settings by using `override_settings` (https://docs.djangoproject.com/en/1.10/topics/testing/tools/#django.test.override_settings)

For backward compatibility the `shop/settings.py` would also return that instance of `AppSettings` from `shop/app_settings`.

**Comment by jrief** [comment]
I never encountered this problem, but I get your point. For ``SHOP_CUSTOMER_SERIALIZER`` ist probably is useless, since that directive should go away anyway, but for all other directives in ``shop.settings.py`` we could follow that approach.

So we can schedule this for 0.9.5.

**Comment by jrief** [comment]
This now is part of version 0.10, so I assume we can close it?
