### ISSUE TITLE
Install 0.9.3 - python 3 ClassName([mixin_type,] enum_type)

### ISSUE THREAD

**Issue by maltitco** [awesto/django-shop#495]
Hi, I try to do new installations using python 3.6 and after:
(shoptutorial)$ cd example
(shoptutorial)$ export DJANGO_SHOP_TUTORIAL=commodity DJANGO_DEBUG=1
(shoptutorial)$ ./manage.py migrate

I got the following error:
`TypeError: new enumerations must be created as `ClassName([mixin_type,] enum_type)``

The problem does not occur with python2.

**Comment by maltitco** [comment]
Tested on Python 3.5 and the error no longer occurs.
Would do well to add this information to the documentation.

**Comment by jrief** [comment]
I did not test django-SHOP with Python-3.6. Up to now, we support 2.7, 3.4 and 3.5
