### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by maltitco** [awesto/django-shop#497]
example:
[https://vimeo.com/198175671](url)

**Comment by jrief** [comment]
in my configuration it works with elasticsearch 1.7.3
Did you run ``./manage rebuild_index``?

What does pip freeze tells?

**Comment by maltitco** [comment]
pip freeze tells:

beautifulsoup4==4.4.0
bs4==0.0.1
defusedxml==0.4.1
Django==1.9.10
django-admin-sortable2==0.6.4
django-allauth==0.23.0
django-angular==0.8.4
django-appconf==1.0.1
django-classy-tags==0.7.2
django-cms==3.3.3
django-compressor==1.6
django-filer==1.2.5
django-filter==0.15.3
django-formtools==1.0
django-fsm==2.4.0
django-fsm-admin==1.2.3
django-haystack==2.5.0
django-ipware==1.1.1
django-mptt==0.8.6
django-parler==1.6.4
django-polymorphic==1.0.2
django-post-office==2.0.8
django-rest-auth==0.5.0
django-sass-processor==0.5.3
django-sekizai==0.10.0
Django-Select2==5.8.9
-e git+https://github.com/awesto/django-shop@9c242411373e5c96b5beba3d79209be148445151#egg=django_shop
django-treebeard==4.1.0
djangocms-admin-style==1.2.6.2
djangocms-bootstrap3==0.1.1
djangocms-cascade==0.11.1
djangocms-text-ckeditor==3.0.1
djangorestframework==3.2.5
djangoshop-stripe==0.2.0
drf-haystack==1.5.6
easy-thumbnails==2.3
elasticsearch==1.7.0
html5lib==0.9999999
jsonfield==1.0.3
libsass==0.8.3
oauthlib==1.0.3
Pillow==3.3.0
pluggy==0.3.1
py==1.4.30
Pygments==2.0.2
python-dateutil==2.5.3
python-openid==2.2.5
python3-openid==3.0.10
pytz==2015.7
requests==2.7.0
requests-oauthlib==0.5.0
six==1.9.0
stripe==1.37.0
Unidecode==0.4.18
urllib3==1.12
virtualenv==13.1.2

./manage.py rebuild_index give:

elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x1083052e8>: Failed to establish a new connection: [Errno 61] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x1083052e8>: Failed to establish a new connection: [Errno 61] Connection refused)

**Comment by jrief** [comment]
> ./manage.py rebuild_index give:
> elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x1083052e8>: Failed to establish a new connection: [Errno 61] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x1083052e8>: Failed to establish a new connection: [Errno 61] Connection refused)

well, then Django is unable to connect to the Elastic REST interface. Please refer to the ES documentation and check how to setup.
