### ISSUE TITLE
How to add some products to cart?

### ISSUE THREAD

**Issue by vivazzi** [awesto/django-shop#498]
My shop needs to add some products to cart. Look to screen:
![test product](https://cloud.githubusercontent.com/assets/11954799/21681032/323e19c0-d345-11e6-8d4c-cdc4c558c647.png)

I take screen from real working shop, which sales wholesale products, so there are some input fields under corresponding size label. At this moment I can add one product only. You can test on page http://xn--i1afgbfs.xn--p1ai/shop/tops/testovyj-produkt

I placed two buttons. One of them is standart behavior (product-add2cart.html), which works very well. Second button is my trying - I cannot realize functionality of adding of some product. Unfortunatelly, I don't know how do it with angular. My tryings fails.

Could you help me?

And I think that django-shop needs more complex examples. I ready to add cloth example to django-shop as PR. Although I haven't cool programmer knowledge for it, but I want to help development of django-shop.

**Comment by jrief** [comment]
In this situation, you have to create your own ``AddToCartSerializer`` with 3 quantity fields.

Then in your router, you attach it to the view, for instance:

```
urlpatterns = [
    ...
    url(r'^(?P<slug>[\w-]+)/add-to-cart', AddToCartView.as_view(
        serializer_class=MyCustomAddToCartSerializer,
    )),
    ...
]
```

you also might need to create your own AngularJS directive, which is quite simple. Use the directive ``shopAddToCart`` from catalog.js as a blueprint.

btw. in one of my customers B2B projects, I added a Serializer, so that his customers can add products in the catalog's list view.

**Comment by vivazzi** [comment]
Thank you for fast answer! Using the own AddToCartSerializer is easy for me. Problem is angular.. 
I'd like to look to your implemention of Serializer for customers B2B projects! 

And how about add test cloth model to django-shop? I'm not sure that I and other developers can use angular for realized shop's task correctly (maybe I mistake). For example, for selection by color I use workaround:
```
{% for obj in product.get_product_colors.all %}
    <label for="input_color_id_{{ obj.color_id }}" style="background-color: {{ obj.color_value }}" data-id="{{ obj.color_id }}"></label>
    <input class="color_input" name="color_values" type="radio" value="{{ obj.color_id }}" ng-model="context.extra.color_id" ng-change="updateContext()" id="input_color_id_{{ obj.color_id }}">
{% endfor %}
```
And I hide `<inputs>`, but add styles for `<label>`, so my color changed when I click to corresponding label. I think is bad code. I try to find more clean code, but cannot not find..

I think developers will find good points from this test example if we add cloth model to django-shop. If interesting I can discuss about it in email or another place (not here).

**Comment by jrief** [comment]
If you need a serializer which can handle variants, such as for colored cloth, have a look at the ``AddSmartphoneToCartSerializer``. There the variant is the memory, though.

**Comment by vivazzi** [comment]
Yes, I use `AddSmartphoneToCartSerializer` as begin for me. And it works very well. But I don't know how write angular controller to handle a two or more products.
If I understand correctly I need change `AddToCartCtrl` and/or `ModalInstanceCtrl` in my own `catalog.js`?

**Comment by jrief** [comment]
you can name that file as you want, but you have to import it into the detail catalog page.
But presumably you don't even have to create your own ``AddToCart`` directive, because that directive sends the complete ``$scope.context`` to the REST-API-endpoint.

If you need more than one field, add another input field bound to that scope context. Look at the provided example:

```
<input class="form-control ng-pristine ng-untouched ng-valid ng-valid-min" type="number" min="1" ng-model="context.quantity" ng-model-options="{updateOn: 'default blur', debounce: {'default': 500, 'blur': 0}}" ng-change="updateContext()">
```

what's important here is the ``ng-model="context.quantity"``.

**Comment by vivazzi** [comment]
Thank you, Jacob! I try to apply your code. let this issue is open some times. As soon as I can good result I write here. I think it maybe useful for otehr devs.

**Comment by vivazzi** [comment]
Jacob, I finished my task! But my code looks like bad. I write own addToCart.function()
```
djangoShopModule.controller('AddToCartCtrl', ['$scope', '$http', '$window', '$modal',
                                      function($scope, $http, $window, $modal) {
	...

	var interval_ID;
	var interval_ID_2;

	$scope.addToCart = function(cart_url, extra_context, next_url) {
		var data = [];
		var count = 0;
		var added_products = 0;
		var $change_count = $('.size_c.active .change_count').filter(function () {
			return parseInt($(this).val() > 0) || $(this).val() != '';
        });
		$.each($change_count, function () {
			$scope.context.extra.size = $(this).parents('.col_wr').find('.size').text();
			$scope.context.quantity = parseInt($(this).val());
			var context_2 = angular.copy($scope.context);
			$http.post(updateUrl, context_2).success(function(context) {
				data.push(angular.copy(context));
				count++;
			});
        });

		interval_ID = setInterval(function () {
			if (count == $change_count.length) {
				for (var i = 0, l = $change_count.length; i < l; i++){
					$http.post(cart_url, data[i]).success(function () {
						added_products++;
					});
				}

				clearInterval(interval_ID);
            }
        }, 200);

		interval_ID_2 = setInterval(function () {
			if (added_products == $change_count.length) {
				$window.location.href = next_url;
				clearInterval(interval_ID_2);
            }
        }, 300);
	};

}]);
```

html:
```
{% for obj in product.get_product_colors.all %}
    <div class="size_c{% if obj_select.index == obj.color_id %} active{% endif %}" data-id="{{ obj.color_id }}">
        <div class="size_wr">
            {% for size in obj.sizes.all %}
                <div class="col_wr">
                    <label class="size{% if forloop.counter == 1 %} active{% endif %}">{{ size.value }}</label>
                    <input id="change_count_{{ size.id }}" class="change_count" max="{{ size.quantity }}" min="0" type="number">
                </div>
            {% endfor %}
        </div>
    </div>
{% endfor %}
```

It works. Now I can add a few products (see http://xn--i1afgbfs.xn--p1ai/shop/tops/testovyj-produkt ). 
If you have free time, you can look this code. Or close this issue now.

Thanks for help!

**Comment by jrief** [comment]
Why did you create your own ``addToCartCtrl`` and did not add ``ng-model="context...."`` to the input fields inside the built-in ``shop-add-to-cart`` directive?

**Comment by vivazzi** [comment]
Oh, I'm sorry.. I must been to tell about my solution (workaround) more.
I do so, because I need add two or more products for one time. By other words, I must send set of products to Cart Serializer. But as I understand I can send only one product. So I use loop to send many products (their quantity is count of input quantity field). I try to use `ng-model="context...."` but I get wrong behavior - all quantity filed is updated together:
![test product](https://cloud.githubusercontent.com/assets/11954799/21990588/656a4e1e-dc4a-11e6-866c-129e4db2ff69.png)

then I use:
```
$.each($change_count, function () {
			$scope.context.extra.size = $(this).parents('.col_wr').find('.size').text();
			$scope.context.quantity = parseInt($(this).val());
			var context_2 = angular.copy($scope.context);
			$http.post(updateUrl, context_2).success(function(context) {
				data.push(angular.copy(context));
				count++;
			});
        });
```
to decide this bug.

Then I get list of products `data = [...]`; and post to Cart Serializer:
```
interval_ID = setInterval(function () {
			if (count == $change_count.length) {
				for (var i = 0, l = $change_count.length; i < l; i++){
					$http.post(cart_url, data[i]).success(function () {
						added_products++;
					});
				}

				clearInterval(interval_ID);
            }
        }, 200);
```

I use setInterval for check that I send all 
```
$http.post(updateUrl, context_2).success(function(context) {
				...
			});
```

Second interval_ID_2  is used to know when we need reload page.

**Comment by vivazzi** [comment]
I understand how I can improvement my code!
Now if we have 5 quantity fields, then we send 10 requests to server:
- `/add-to-cart` (5 requests: for updating the product contet for each size)
- `/cart` (5 requests: for adding of products to cart)

I think that I can use 1 request instead of 5 requests of `/add-to-cart` using own Serializer. And maybe I can use angular for changing of quantity.
I can show my results, when I will realize my idea.

**Comment by jrief** [comment]
Before proceeding with DOM manipulations, you should really read this excellent post [“Thinking in AngularJS” if I have a jQuery background?](http://stackoverflow.com/questions/14994391/thinking-in-angularjs-if-i-have-a-jquery-background) on Stackoverflow.

**Comment by vivazzi** [comment]
Thank you Jacob! It really that I need because in Angular I am new. It's good post. I think this issue need close, because this issue lost activity.. Or not close.. How do you think about it?
I'd like to finish my task about adding some products and add solution to here, but it may be long by time.

**Comment by jrief** [comment]
can we close this?

**Comment by rfleschenberg** [comment]
Yup :)

**Comment by vivazzi** [comment]
Yes, it's better to close this issue. My code above is very bad and it should be removed..
This task is specific and I plan to created any use-cases to someone can use it. Maybe it will place on my blog and offer you to include in the docs.. Howbeit I have many ideas and some working code which needs in refactoring. Later I will add some issues. By some reason I can continue my work after April.
