### ISSUE TITLE
LookupError: Model 'email_auth.User' not registered

### ISSUE THREAD

**Issue by raoarun25** [awesto/django-shop#536]
I am trying to setup the project by cloning and installing all the apps listed. when i try to run migrate I am getting the error LookupError: Model 'email_auth.User' not registered. Please help me out

**Comment by jrief** [comment]
did you add this to your settings.py:

```
INSTALLED_APPS = [
    'django.contrib.auth',
    'email_auth',
    ...
```

or do you have a different configuration?

**Comment by raoarun25** [comment]
yes i have already added this to installed apps.

**Comment by jrief** [comment]
I need more information to reproduce this.

**Comment by rfleschenberg** [comment]
It would be ideal if you can give us a link to the project repository so we can reproduce the issue.

**Comment by raoarun25** [comment]
i just tried again and now its throwing me error 
![screen shot 2017-04-07 at 1 09 17 pm]
(https://cloud.githubusercontent.com/assets/26869108/24790131/81bb094a-1b93-11e7-9833-449b860d8d78.png)

RuntimeError: Model class shop.models.notification.Email doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

@rfleschenberg how can I give link to the my project directory??

**Comment by raoarun25** [comment]
![screen shot 2017-04-07 at 2 00 20 pm](https://cloud.githubusercontent.com/assets/26869108/24792200/a33a4764-1b9a-11e7-9fe1-3a461d7b7531.png)

**Comment by jrief** [comment]
First, please use the latest release, not RC3.

From that screenshot, it seems as if you did not add ``shop`` to ``INSTALLED_APPS``.

**Comment by raoarun25** [comment]
hi , 
I am using the latest release and i have also added shop in settings file.

![screen shot 2017-04-11 at 2 23 48 pm](https://cloud.githubusercontent.com/assets/26869108/24900912/ff94e6ba-1ec2-11e7-9d0f-d85c31034ea8.png)

**Comment by rfleschenberg** [comment]
IIRC you also have to add `email_auth`? Or is that not the case anymore?

**Comment by raoarun25** [comment]
I have already added email_auth

**Comment by rfleschenberg** [comment]
Can you give us the exact sequence of commands you ran, so we can reproduce this?

**Comment by raoarun25** [comment]
Hi , i have migrated and running server now . but these are the errors i am getting.

![screenshot from 2017-04-15 11-38-12](https://cloud.githubusercontent.com/assets/26869108/25062255/e39ce760-21e6-11e7-9334-5bb9a4df6f51.png)
![screenshot from 2017-04-15 11-37-16](https://cloud.githubusercontent.com/assets/26869108/25062256/e836d59c-21e6-11e7-9315-7595a79b0f22.png)

i am following these commands:
http://django-shop.readthedocs.io/en/stable/tutorial/intro.html (ref)

(shoptutorial)$ cd example
(shoptutorial)$ export DJANGO_SHOP_TUTORIAL=commodity DJANGO_DEBUG=1
(shoptutorial)$ ./manage.py migrate
(shoptutorial)$ ./manage.py createsuperuser
Email address: admin@example.org
Username: admin
Password:
Password (again):
Superuser created successfully.
(shoptutorial)$ ./manage.py runserver

**Comment by rfleschenberg** [comment]
I can confirm that we have a bug in the docs. the `package.json` file has moved into the `example` directory, the docs do not reflect that change.

**Comment by rfleschenberg** [comment]
Ah sorry, I was looking at the docs for the wrong version.

**Comment by jrief** [comment]
@raoarun25 
```
cd example
npm install
```

should install the NodeJS dependencies.

**Comment by rfleschenberg** [comment]
@raoarun25 Can you please delete your `Tutorial` directory and try if the following sequence of commands works for you?

```
mkdir Tutorial; cd Tutorial
virtualenv -p $(which python3) shoptutorial
source shoptutorial/bin/activate
git clone --depth 1 https://github.com/awesto/django-shop
cd django-shop
pip install -U pip setuptools
pip install -r requirements/common.txt
pip install --no-deps -e .
pip install 'Django<1.11'
cd example
npm install
export DJANGO_SHOP_TUTORIAL=commodity DJANGO_DEBUG=1
./manage.py migrate
./manage.py createsuperuser
./manage.py runserver
```

Thanks!

**Comment by jrief** [comment]
@raoarun25 Please recheck with version 0.11. Yesterday I retested, if the documentation corresponds to the actual setup, and it does.
Otherwise please reopen this issue.

**Comment by 2251701712** [comment]
> I am trying to setup the project by cloning and installing all the apps listed. when i try to run migrate I am getting the error LookupError: Model 'email_auth.User' not registered. Please help me out

I have same question now，can you help me

**Comment by jrief** [comment]
Did you create a project using the cookiecutter-django-shop template?

Did you check if `'email_auth'` has been added to your `INSTALLED_APPS`?

**Comment by 2251701712** [comment]
> Did you create a project using the cookiecutter-django-shop template?
> 
> Did you check if `'email_auth'` has been added to your `INSTALLED_APPS`?

Yes, wether the django version is required？

**Comment by 2251701712** [comment]
![image](https://user-images.githubusercontent.com/45872979/59415380-f34e2700-8df5-11e9-9cbb-4621af5f2cff.png)

**Comment by 2251701712** [comment]
![image](https://user-images.githubusercontent.com/45872979/59415487-2d1f2d80-8df6-11e9-9369-0b255179e765.png)

**Comment by 2251701712** [comment]
![image](https://user-images.githubusercontent.com/45872979/59415757-aa4aa280-8df6-11e9-9e4b-e5b567f96b15.png)

**Comment by jrief** [comment]
rather than providing screenshots with error messages, please write some step-by-step instructions on how to reproduce this.
This btw. is not the correct way to ask for help on Open Source projects anyway.
