### ISSUE TITLE
Error with search trying tutorial

### ISSUE THREAD

**Issue by ilyaglar** [awesto/django-shop#539]
I got an error while trying tutorial - after populating the database using fixtures any manage.py execution throws:
TypeError: 'RegexURLPattern' object is not iterable

This is somehow connected to search module - after deleting "search" page from cms all works.
Tried on ubuntu, both 16.10 and clean 16.04, docker image works right too.

**Comment by jrief** [comment]
Thanks for reporting this regression, I'm currently fixing this.

**Comment by jrief** [comment]
If you want to help out, please confirm this fix using the branch below, to speed up the peer review process:
https://github.com/jrief/django-shop/tree/fixes/359-TypeError-RegexURLPattern

**Comment by ilyaglar** [comment]
Now all works perfectly, i see no errors.

**Comment by ilyaglar** [comment]
btw, i think its good idea to mention at first  tutorial page, that without installling elasticsearch and runninig:
 ./manage.py rebuild_index --noinput
search would not work.

**Comment by jrief** [comment]
If you start with Docker, the Index is built 10 minutes after the container was fired up.
The docs about searching mention how to build the index. Where do you miss this information?

**Comment by rfleschenberg** [comment]
We are missing that information here: http://django-shop.readthedocs.io/en/latest/tutorial/intro.html

**Comment by rfleschenberg** [comment]
We should document how to install ES, and that the user has to run `rebuild_index`.
