### ISSUE TITLE
Should CMSPageRenderer support rendering non CMS templates?

### ISSUE THREAD

**Issue by dinoperovic** [awesto/django-shop#549]
Is the `CMSPageRenderer` meant to support only rendering of CMS pages via apphooks?

I have a case where using apphooks to set the urls is optional. So for example you could attach an apphook of CatalogListApp to a page, or include the catalog urls manually. In which case I get an error: `'NoneType' object has no attribute 'publisher_is_draft'` because `request.current_page` is None.

By checking for current page before setting edit mode enables this: 
```python
if request.current_page:
    # set edit_mode, so that otherwise invisible placeholders can be edited inline
    template_context['edit_mode'] = request.current_page.publisher_is_draft
```

**Comment by rfleschenberg** [comment]
Yes, the CMSPageRenderer assumes an apphook attached to a django-cms page. Can you solve your problem by using a custom renderer?

**Comment by dinoperovic** [comment]
@rfleschenberg Yes, I have created a modified renderer to support this.
