### ISSUE TITLE
Error applying shop.0004_ckeditor31 migration.

### ISSUE THREAD

**Issue by dinoperovic** [awesto/django-shop#550]
I get this error trying to run `shop.0004_ckeditor` migration, using MySQL:

```zsh
django.db.utils.OperationalError: (1093, "You can't specify target table 'cms_cmsplugin' for update in FROM clause")
```
Maybe has to do with this?
http://stackoverflow.com/questions/4429319/you-cant-specify-target-table-for-update-in-from-clause

When I Changed:
```python
"SELECT id FROM  cms_cmsplugin WHERE plugin_type='AcceptConditionFormPlugin');"
```
to:
```python
"SELECT id FROM (SELECT * FROM cms_cmsplugin) AS plugins WHERE plugin_type='AcceptConditionFormPlugin');"
```

the migrations ran fine.

**Comment by jrief** [comment]
Thanks for reporting.
Could you please create a pull request.

@rfleschenberg shall we add mysql and postgres to the testing matrix, currently django-shop does not use raw SQL statements, except for migrations.

**Comment by rfleschenberg** [comment]
Testing on Postgres and MySQL seems like a good idea.

I am surprised that this error only pops up now. Nobody ran this migration on MySQL before? Anyway, thanks for the PR!
