### ISSUE TITLE
Install ./manage.py initialize_shop_demo

### ISSUE THREAD

**Issue by maltitco** [awesto/django-shop#574]
Is issues on install demo shop:
after command:
./manage.py initialize_shop_demo
Error:
zipfile.BadZipFile: File is not a zip file

**Comment by jrief** [comment]
Thanks for reporting. I fixed the broken link.
Please retest and close.

**Comment by maltitco** [comment]
Now everything works fine.

**Comment by calvinkcc** [comment]
I'm having this error as well. 
"File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file"
