### ISSUE TITLE
[Question] Taxes

### ISSUE THREAD

**Issue by maltitco** [awesto/django-shop#575]
Hi, I have 2 question:
1. where can i find documentation about taxes?
Use Cart Modifiers to handle tax in documentation is empty.

2. It is possible to have different tax value to different product?

**Comment by jrief** [comment]
Taxes are handled using a CartModifier. There are two samples on how to handle taxes, one for the European model and one for the U.S. model, but you can handle them, however you want.

If you need different rates for each product, then I would add a tag to the product model and
write your own TaxCartModifier.

I admit that this should be better documented.

**Comment by maltitco** [comment]
Thanks for the clarification.
I'm waiting for the documentation update.

**Comment by jrief** [comment]
just updated docs/howtos/handling-taxes.rst
please review and close

**Comment by maltitco** [comment]
Jacob, thank you very much for completing the documentation.
I will test these methods, I will let you know how they are doing.
