### ISSUE TITLE
ProcessNextStepPlugin doesn't display in plugin list

### ISSUE THREAD

**Issue by typefj** [awesto/django-shop#578]
I try to add ProcessNextStepPlugin to Process Step, but I can't find ProcessNextStepPlugin in Plugin List.

**Comment by jrief** [comment]
This is (was) a bug in **djangocms-cascade**. It has been fixed and will be available in the next release.
Please retry with the latest commit from https://github.com/jrief/djangocms-cascade and let me know if it works for you.

**Comment by typefj** [comment]
It works! Thanks!

**Comment by jrief** [comment]
please use djangocms-cascade==0.12.5
