### ISSUE TITLE
upgrade node modules in version >=0.10.0

### ISSUE THREAD

**Issue by racitup** [awesto/django-shop#580]
Hi,

I notice the `package.json` required by npm has been moved into the subfolder `example` as of version 0.10.
It appears according to [this thread](https://github.com/npm/npm/issues/2974) that npm does not have the ability to install from a package file in a subfolder of a repo. I used to use `npm install git://github.com/awesto/django-shop.git#0.9.2` which now fails with an error.

Is there a workaround for this or could the `package.json` be moved back to the repo root? I consider the npm packages a requirement of the framework, not just of the example anyway...

**Comment by jrief** [comment]
The new documentation says:
```
cd example
npm install
```

The reason I moved it is, that in my opinion, node packages shall be managed by the project, and not by the Django app. In example, myshop is the project.

**Comment by racitup** [comment]
For anyone else wanting to upgrade their node modules for an existing project, here are the steps as of version 0.10:

To update node module dependencies:

1. install npm
2. find the version of django-shop installed through pip (0.10.2):
`pip show django-shop`
3. create a temp folder for the django-shop repository
4. clone the repo at that tag:
`git clone git@github.com:awesto/django-shop.git --branch 0.10.2 --single-branch`
5. copy the package.json to your static folder that will contain 'node_modules':
`cp django-shop/example/package.json path/to/your/project/static/`
6. remove the temporary repo
`rm -rf django-shop`
7. change to your static folder and rename your old 'node_modules'
`cd path/to/your/project/static/`
`mv node_modules node_modules_old`
8. install new modules
`npm install`
9. check (diff -rq node_modules node_modules_old) and once happy remove your old node_modules
`rm -rf node_modules_old`

NB: Bower is no longer used
NB2: No, github doesn't support [git archive](https://www.gilesorr.com/blog/git-archive-github.html)

**Comment by raratiru** [comment]
Thank you @racitup .It would be great to include this in the docs.
