### ISSUE TITLE
Any idea why payment & shipping method forms in checkout are greyed out?

### ISSUE THREAD

**Issue by racitup** [awesto/django-shop#584]
My cart modifiers looks like below but the forms on the checkout page for both payment and shipping are greyed out.. any idea what the problem is? I'm using v0.10.2

```
SHOP_CART_MODIFIERS = (
    # provides the default cart lines
    'myproducts.modifiers.CurrencyCartModifier',
    # bulk order discounts
    'myproducts.modifiers.QuantityDiscountModifier',
    # unit prices are gross so it calculates VAT already applied
    'shop.modifiers.taxes.CartExcludedTaxModifier',
    # basic shipping provider for £5
    'myproducts.modifiers.PostalShippingModifier',
    # customer can pick up the goods
    'shop.modifiers.defaults.SelfCollectionModifier',
    # payment is out-of-band
    'shop.modifiers.defaults.PayInAdvanceModifier',
    # stripe payment
    'myproducts.modifiers.StripePaymentModifier'
)
```
[![Screen Shot 2017-05-30 at 23.59.01.png](https://s16.postimg.org/71one8dt1/Screen_Shot_2017-05-30_at_23.59.01.png)](https://postimg.org/image/oeyxt3941/)

**Comment by jrief** [comment]
How does the HTML markup look like?

**Comment by racitup** [comment]
For just the two form elements:
`<form shop-dialog-form="" name="payment_method_form" novalidate="" class="ng-invalid ng-invalid-required ng-valid-parse ng-pristine cms-plugin cms-plugin-471"><div class="djng-line-spreader"><ul class="djng-form-errors" ng-show="payment_method_form.$pristine"><li ng-show="payment_method_form.$message" class="invalid ng-binding ng-hide" ng-bind="payment_method_form.$message"></li></ul><ul class="djng-form-errors ng-hide" ng-show="payment_method_form.$dirty"></ul></div><div class="has-feedback djng-field-required form-group"><label class="control-label djng-field-required" for="id_payment_modifier_0">Payment Method</label><div validate-multiple-fields="payment_modifier"><div class="radio"><label for="id_payment_modifier_0"><input id="id_payment_modifier_0_0" name="payment_modifier" ng-change="upload()" ng-model="data.payment_method['payment_modifier']" type="radio" value="pay-in-advance" required="" class="ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required"> Pay in advance</label></div><div class="radio"><label for="id_payment_modifier_1"><input id="id_payment_modifier_1_1" name="payment_modifier" ng-change="upload()" ng-model="data.payment_method['payment_modifier']" type="radio" value="stripe-payment" required="" class="ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required"> Credit Card</label></div><div class="radio"><label for="id_payment_modifier_2"><input id="id_payment_modifier_2_2" name="payment_modifier" ng-change="upload()" ng-model="data.payment_method['payment_modifier']" type="radio" value="stripe-payment" required="" class="ng-pristine ng-untouched ng-invalid ng-invalid-required ng-empty"> Credit Card</label></div></div><ul class="djng-form-control-feedback djng-field-errors" ng-show="payment_method_form['payment_modifier'].$pristine"><li ng-show="payment_method_form.payment_modifier.$message" class="invalid ng-binding ng-hide" ng-bind="payment_method_form.payment_modifier.$message"></li></ul><ul class="djng-form-control-feedback djng-field-errors ng-hide" ng-show="payment_method_form['payment_modifier'].$dirty"><li ng-show="payment_method_form['payment_modifier'].$error.required" class="invalid">This field is required.</li><li ng-show="payment_method_form['payment_modifier'].$valid" class="valid ng-hide"></li></ul><input class="form-control ng-untouched ng-valid ng-not-empty ng-valid-parse ng-pristine" id="id_plugin_id" name="plugin_id" ng-model="data.payment_method['plugin_id']" type="hidden" value="471" autocomplete="off"><input class="form-control ng-untouched ng-valid ng-not-empty ng-valid-parse ng-pristine" id="id_plugin_order" name="plugin_order" ng-model="data.payment_method['plugin_order']" type="hidden" value="5" autocomplete="off"></div></form>`

`<form shop-dialog-form="" name="shipping_method_form" novalidate="" class="ng-invalid ng-invalid-required ng-valid-parse ng-pristine cms-plugin cms-plugin-272"><div class="djng-line-spreader"><ul class="djng-form-errors" ng-show="shipping_method_form.$pristine"><li ng-show="shipping_method_form.$message" class="invalid ng-binding ng-hide" ng-bind="shipping_method_form.$message"></li></ul><ul class="djng-form-errors ng-hide" ng-show="shipping_method_form.$dirty"></ul></div><div class="has-feedback djng-field-required form-group"><label class="control-label djng-field-required" for="id_shipping_modifier_0">Shipping Method</label><div validate-multiple-fields="shipping_modifier"><div class="radio"><label for="id_shipping_modifier_0"><input id="id_shipping_modifier_0_0" name="shipping_modifier" ng-change="upload()" ng-model="data.shipping_method['shipping_modifier']" type="radio" value="postal-shipping" required="" class="ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required"> Postal shipping</label></div><div class="radio"><label for="id_shipping_modifier_1"><input id="id_shipping_modifier_1_1" name="shipping_modifier" ng-change="upload()" ng-model="data.shipping_method['shipping_modifier']" type="radio" value="self-collection" required="" class="ng-pristine ng-untouched ng-invalid ng-invalid-required ng-empty"> Self collection</label></div></div><ul class="djng-form-control-feedback djng-field-errors" ng-show="shipping_method_form['shipping_modifier'].$pristine"><li ng-show="shipping_method_form.shipping_modifier.$message" class="invalid ng-binding ng-hide" ng-bind="shipping_method_form.shipping_modifier.$message"></li></ul><ul class="djng-form-control-feedback djng-field-errors ng-hide" ng-show="shipping_method_form['shipping_modifier'].$dirty"><li ng-show="shipping_method_form['shipping_modifier'].$error.required" class="invalid">This field is required.</li><li ng-show="shipping_method_form['shipping_modifier'].$valid" class="valid ng-hide"></li></ul><input class="form-control ng-untouched ng-valid ng-not-empty ng-valid-parse ng-pristine" id="id_plugin_id" name="plugin_id" ng-model="data.shipping_method['plugin_id']" type="hidden" value="272" autocomplete="off"><input class="form-control ng-untouched ng-valid ng-not-empty ng-valid-parse ng-pristine" id="id_plugin_order" name="plugin_order" ng-model="data.shipping_method['plugin_order']" type="hidden" value="6" autocomplete="off"></div></form>`

**Comment by racitup** [comment]
Could it be something I've missed in the configuration since I've upgraded from 0.9.2?

**Comment by jrief** [comment]
Did you use the example shop as a base?
Any Javascript errors?

**Comment by racitup** [comment]
I used 0.9.2 as a base a long time ago and have recently been through fixing all the changes to 0.10.2. So I have fixed all of the Javascript errors..
My next plan was to get a fresh example shop going to see if that works and try to figure out what the differences are. I just thought there might be something obvious that I've missed..

**Comment by jrief** [comment]
always difficult to tell, if you can't reproduce it.

**Comment by racitup** [comment]
It seems I'm missing something out of `shop/css/_django-shop.scss`. Is there a guide to the styling? I can't seem to find what the minimum scss required to make all the CMS plugins and forms work is.
Thanks for the input!

**Comment by racitup** [comment]
It looks like I'm also overriding something important. I'll figure it out, thanks.
