### ISSUE TITLE
Order with empty cart

### ISSUE THREAD

**Issue by maltitco** [awesto/django-shop#587]
It is possible to place an order when the cart is empty:
https://vimeo.com/219814398

**Comment by jrief** [comment]
This is intended, although I agree that it doesn't make a lot of sense :)

However, there is a simple, yet not optimal solution. If you override the template ``myshop/cart/editable.html`` you can use the context variable ``is_cart_filled`` to test against an empty cart.

You then must move the "Proceed to checkout" button as child of the cart plugin.

**Comment by racitup** [comment]
It also seems like the code tries to save a cart that doesn't exist..
I'm creating my own forms that use the DialogModelForm mechanism and am getting `NOT NULL constraint failed: myproducts_cart.customer_id` when it saves the cart. The cart is empty and doesn't have a pk.
I noticed the below in shop.models.cart, should "force_update is False" be "True"?

```
    def save(self, force_update=False, *args, **kwargs):
        if self.pk or force_update is False:
            super(BaseCart, self).save(force_update=force_update, *args, **kwargs)
```

**Comment by racitup** [comment]
Ah no, I understand, there's also a `force_insert` which is mutually exclusive to `force_update`.

**Comment by jrief** [comment]
In version 0.11 the cart shows a message, if nothing is inside.
Please create a new issue if this pop up again.
