### ISSUE TITLE
Docker Install Freezes on OSX Sierra

### ISSUE THREAD

**Issue by artforlife** [awesto/django-shop#591]
I am following the following tutorial using the Docker route and am encountering a difficulty: http://django-shop.readthedocs.io/en/latest/tutorial/quickstart.html#tutorial-prepared-docker-image

After I run this command `docker run --name demo-shop-i18n_polymorphic --env DJANGO_SHOP_TUTORIAL=i18n_polymorphic -p 9001:9001 awesto/django-shop-demo:latest` I see a few items being downloaded. However, the process seems to freeze at the following step:

> setting capability setuid [7]

I have waited as long as one hour and tried to re-do the entire thing twice to no avail. Could anyone suggest what is going on?

**Comment by maltitco** [comment]
I tested the latest and 10.0.1 tag and I have the same issue if i use:

> docker run --name demo-shop-i18n_polymorphic --env DJANGO_SHOP_TUTORIAL=i18n_polymorphic -p 9001:9001 awesto/django-shop-demo:latest

Try it that way:
1. docker pull awesto/uwsgi-django-shop
2. docker start demo-shop-i18n_polymorphic

I tested it and it worked for me - in the browser enter 0.0.0.0:9001

**Comment by jrief** [comment]
Yesterday I uploaded new Docker containers to the Hub. Please retry with
```
docker run --name demo-shop-i18n_polymorphic --env DJANGO_SHOP_TUTORIAL=i18n_polymorphic -p 9001:9001 awesto/django-shop-demo:latest

```

**Comment by denizs** [comment]
I'm experiencing the same thing @jrief! Build freezes at `setting capability setuid [7]` ☹️

**Comment by jrief** [comment]
You mean `docker build.... ` freezes?

**Comment by denizs** [comment]
Argh! sorry for using that ambiguous term 😆 I mean that your instructions to get the demo up and running, that is `docker run...`, freezes with the very same last line as for @artforlife

**Comment by denizs** [comment]
Thanks @maltitco, your advice did it for me!

**Comment by jrief** [comment]
`docker run ... ` can take several minutes before delivering content. This is because some media files have to be downloaded.
