### ISSUE TITLE
Is it possible to remove fields from Customer Form?

### ISSUE THREAD

**Issue by racitup** [awesto/django-shop#603]
I have added fields to the customer model, but these fields appear on the checkout page because the Customer Form plugin shows all model fields. Is there a way to select or exclude fields?

**Comment by vivazzi** [comment]
@racitup I think you need override Customer Form, for example for GuestForm:
In /shop/cms_plugins.py
```
plugin = plugin_pool.get_plugin('GuestFormPlugin')  # of CustomerFormPlugin in your case
plugin.form_class = 'myshop.forms.GuestForm'
```

In /shop/forms.py
```
class GuestForm(GuestFormBase):
    ...
    # specific fields, for example 'phone = fields.CharField()' and others...
    
    class Meta:
        ...
        exclude = ('user', 'recognized', 'number', 'last_access')  # in here you can exclude nesessary fields
        ...

```
Find CustomerForm in /shop/forms/checkout.py and override.

I hope, this is method is right. Fix me, if it is not so.

**Comment by racitup** [comment]
Thanks @vivazzi! Which django-shop version are you using? This doesn't match what I have in 0.10.2..

**Comment by racitup** [comment]
Any ideas why this doesn't show anything?

```
from shop.forms.checkout import CustomerForm

class CustomerFormMinimal(CustomerForm):
    class Meta:
        model = Customer
        custom_fields = fields = ('email', 'first_name', 'last_name')
```

**Comment by jrief** [comment]
I never inherited from ``CustomerForm``, but these fields are faked, in that sense, as they belong to the ``User`` model.
Try to replicate the ``CustomerForm`` and remove the fields you don't want.

**Comment by racitup** [comment]
Found it, just needed to override the form name:
```
form_name = 'customer_form'  # Override form name to reuse template `customer-form.html`
```
