### ISSUE TITLE
Error messgae while intsalling using pyhton install.py

### ISSUE THREAD

**Issue by mehtaaditya** [awesto/django-shop#605]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 20600: character maps to <undefined>

**Comment by jrief** [comment]
please provide more information

**Comment by mehtaaditya** [comment]
using cmd i used the command python install setup.py,it then shop an error message' File "C:\Users\Aditya\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 20600: character maps to <undefined>' 
i tried to find soltion to this problem but didnt find any
any help is appreciated
