### ISSUE TITLE
Error messgae while intsalling using pyhton install.py

### ISSUE THREAD

**Issue by mehtaaditya** [awesto/django-shop#607]
using cmd i used the command python install setup.py,it then shop an error message' File "C:\Users\Aditya\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1250.py", line 23, in decode
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 20600: character maps to '
i tried to find soltion to this problem but didnt find any
any help is appreciated

**Comment by maltitco** [comment]
Check the installation on Python 3.5

**Comment by jrief** [comment]
seems to be related to some kind of UTF-8 encoding problem but not to django-SHOP.
