### ISSUE TITLE
angular scope not updating with plugin_order & plugin_id

### ISSUE THREAD

**Issue by racitup** [awesto/django-shop#608]
I'm overriding the GuestForm plugin and form like below, but when put on a CMS page with a Proceed Button I get the following error because the angular scope does not contain plugin_order & plugin_id, hence the upload() request doesn't either.
The normal Guest Form seems to work fine in the same way.

Any idea why?

```
File "/Users/rich/Documents/source/django-shop/shop/views/checkout.py", line 65, in <lambda>
    dialog_data = sorted(dialog_data, key=lambda tpl: int(tpl[1]['plugin_order']))
TypeError: string indices must be integers
```

```
class RegisterSubscriptionFormPlugin(CustomerFormPluginBase):
    name = _("Register Subscription Form")
    form_class = 'shop_subscribe.forms.RegisterSubscriptionForm'
DialogFormPluginBase.register_plugin(RegisterSubscriptionFormPlugin)
```

```
class RegisterSubscriptionForm(GuestForm):
    legend = _("Subscribe to product updates")
```

**Comment by jrief** [comment]
I assume you added them manually, not through Cascade?
Then you have to specify at least the priority, otherwise the REST endpoint does not know how to sort the various form datas.

For those rendering forms manually, this should be better documented.

**Comment by racitup** [comment]
I was using it in a CMS placeholder.
I think the differences were a different placeholder than the shop 'Main Content', and the template was also different. Would that make a difference? It appears to be fixed now but I have another error I need to fix..

**Comment by racitup** [comment]
Seems to be fixed. Again, not sure what I did to fix it 😕
