### ISSUE TITLE
'This field is required' error on DialogForm reload?

### ISSUE THREAD

**Issue by racitup** [awesto/django-shop#611]
Any idea why the form validation causes a `This field is required.` error after form submission but before the page reloads as below?
I'm using a custom overridden GuestForm plugin and a Proceed Button plugin on a CMS page placeholder.
I've tried breakpointing the `dialogs.js` but it seems to happen after all that code.

![required_anim](https://user-images.githubusercontent.com/18157195/27568778-8fa9105a-5aeb-11e7-968d-b2f808fd68fb.gif)

**Comment by jrief** [comment]
Hmm, difficult to say.
"Subscribe to product updates" would be a nice feature anyway. Could you please create an issue and add your requirements.

**Comment by racitup** [comment]
Ah, sorry I forgot I opened this. No need for requirements, already fixed! :wink:
[djangoshop-subscribe](https://github.com/racitup/djangoshop-subscribe)
