### ISSUE TITLE
Modules in common.txt not installed through pip install django-shop

### ISSUE THREAD

**Issue by raratiru** [awesto/django-shop#615]
The following modules were not installed with `pip install django-shop` although they are included in [common.txt](https://github.com/awesto/django-shop/blob/master/requirements/common.txt)

* django-filter
* django-sass-processor
* django-compressor
* djangocms-bootstrap3

**Comment by jrief** [comment]
This is because we have hard and soft dependencies. Soft dependencies are handles by ``common.txt``.
... I know, not a very nice solution ...

**Comment by raratiru** [comment]
OK, I just found [this post](https://github.com/awesto/django-shop/issues/580) on how to install the npm modules. 

So, I can do something similar for the common.txt.
