### ISSUE TITLE
TypeError: new enumerations must be created as `ClassName([mixin_type,] enum_type)`

### ISSUE THREAD

**Issue by ghotiv** [awesto/django-shop#616]
step by step  (django 1.9 python3.6)
1.2.1. Create a database for the demo
(shoptutorial)$ cd django-shop/example
(shoptutorial)$ export DJANGO_SHOP_TUTORIAL=commodity DJANGO_DEBUG=1
(shoptutorial)$ ./manage.py migrate

then occur this eoor

**Comment by danmir** [comment]
I had the same problem - switched to Python 3.5.0

**Comment by maltitco** [comment]
In my experience django-shop does not work properly with python 3.6.

On the other hand, if you do everything as it is in the tutorial in points:
1.2. Prepare the Installation
and next in:
1.2.2. Populate the Database using Fixtures
You will get a demo of the store with all the possibilities.

**Comment by jrief** [comment]
yes, unfortunately django-SHOP and some of its dependencies are not Python-3.6 ready.

**Comment by racitup** [comment]
Ah, I think this also means you can't currently use heroku with Django-SHOP since it only supports python-3.6.2 & python-2.7.13 ? Or is 2.7.13 still supported?
