### ISSUE TITLE
Add a frontend lib (Font Awesome)

### ISSUE THREAD

**Issue by DrMartiner** [awesto/django-shop#617]
Hello,

How can I add a frontend lib to the WEB Pack bundle? (I want to add Font Awesome)

Best regards,
Aleksei

**Comment by jrief** [comment]
No, because Font Awesome can be easily be integrated using djangocms-cascade's font upload feature. For details please read: http://djangocms-cascade.readthedocs.io/en/latest/icon-fonts.html

(... except you have a special use-case where this feature doesn't fit...)

**Comment by DrMartiner** [comment]
@jrief Thanks a lot!
