### ISSUE TITLE
Customer order list

### ISSUE THREAD

**Issue by maltitco** [awesto/django-shop#618]
The order list for the customer is limited to 12. This causes the customer to be unable to access older orders.

**Comment by rfleschenberg** [comment]
Thanks! This should not be too hard to fix (famous last words). Do you want to submit a PR? :)

**Comment by maltitco** [comment]
I'll leave it for later, now I'm fighting the payment module.

**Comment by jrief** [comment]
Ups....
This is because the `OrderListSerializer` paginates by default. It should be enough to copy the paginator HTML snippet from the Catalog List View into the Order List View.

**Comment by jrief** [comment]
you can apply this patch to your ``shop/order/list.html`` template:
https://github.com/awesto/django-shop/commit/210b20e712db587dede904396789481c2ab31334

**Comment by jrief** [comment]
this is already part of the branch: releases/0.11
