### ISSUE TITLE
Stripe payments "out of core"?

### ISSUE THREAD

**Issue by maltitco** [awesto/django-shop#620]
Hi, I think Stripe Payments should be off the core django-shop core.
For now, you still need to install it as module anyway.

**Comment by jrief** [comment]
Stripe payments are optional. Where are you forced by the default installation to use them?

**Comment by maltitco** [comment]
Looking at the code in several places I noticed that in this example:
In settings "if 'shop_stripe' in INSTALLED_APPS: ..."

This is just my suggestion to strive for the full modularity of the project.

**Comment by jrief** [comment]
It's OK to have that in the example code, after all we want to add a PSP to our project, don't we?

Therefore I added Stripe, since it has the best API.
