### ISSUE TITLE
Add to cart calculation does not use the cart modifiers?

### ISSUE THREAD

**Issue by racitup** [awesto/django-shop#627]
When changing the quantity on the add to cart dialog, the calculated amount isn't the same as when in the cart due to the modifiers. Is this intentional or is there a way to fix it?

**Comment by racitup** [comment]
This is due to the following line in `shop.serializers.defaults.AddToCartSerializer`:
`instance.setdefault('subtotal', instance['quantity'] * instance['unit_price'])`

The serializer documentation says: 

> Since we may create our own Add this Product to Cart Serializer for each product type in our shop, hence overriding its functionality with a customized implementation, such a serializer may return any other information relevant to the customer. This could for instance be a rebate or just an update of the availability.

So I guess I just override the default. Are there any plans to change the default serializer to use the cart modifiers instead of the hard-coded calculation?

**Comment by jrief** [comment]
You can replace the default serializer with a customized one. For instance, the default cart modifier of one of my customers is:

```
class CustomerCartModifier(DefaultCartModifier):
    def arrange_watch_items(self, watch_items, request):
        """
        Removed duplicates from the watch list.
        """
        prev_product_id = None
        exclude_item_ids = []
        for item_id, product_id in watch_items.order_by('product').values_list('id', 'product'):
            if product_id == prev_product_id:
                exclude_item_ids.append(item_id)
            prev_product_id = product_id
        return watch_items.exclude(id__in=exclude_item_ids)

    def arrange_cart_items(self, cart_items, request):
        cart_items = cart_items.order_by('pk')
        return cart_items

    def pre_process_cart(self, cart, request):
        cart.extra['num_samples'] = 0
        cart.save(force_update=True)

    def pre_process_cart_item(self, cart, cart_item, request):
        # here I handle free samples
        # (... customer specific code ...)
        cart_item.save()

    def process_cart_item(self, cart_item, request):
        # here I handle the line_total including free sample
        # (... customer specific code ...)

    def add_extra_cart_row(self, cart, request):
        # here I handle discounts

    def post_process_cart(self, cart, request):
        cart.save(force_update=True)
```

**Comment by racitup** [comment]
I have customised my modifiers too. Shouldn't the default serializer use the modifier pool too though?

**Comment by racitup** [comment]
I've implemented a modification to my AddToCartSerializer and works fine just running all the `*process_cart_item` methods in the modifier pool instead of the hard-coded calculation. Should I submit a PR? It's a bit of a hack using a dummy cartitem model object because of course it won't be in the cart/db yet.

Also whilst doing that I got an error for `shop.views.catalog.AddToCartView.get()`:

> AssertionError: When a serializer is passed a `data` keyword argument you must call `.is_valid()` before attempting to access the serialized `.data` representation.
You should either call `.is_valid()` first, or access `.initial_data` instead.

Should 
`return Response(serializer.data)`
actually be
`return Response(serializer.initial_data)`?

I can include that in the PR..

**Comment by jrief** [comment]
> Should
> return Response(serializer.data)

did I miss to call ``serializer.is_valid()`` before?

Ups, yes then it's a bug!

**Comment by racitup** [comment]
Ah ignore that bug. It was only when I accidentally passed in data to the view get() serializer. It seems initial_data doesn't exist.

**Comment by jrief** [comment]
can I close this?

**Comment by racitup** [comment]
If you think it is acceptable that the add to cart subtotal may not match the cart line total?

**Comment by jrief** [comment]
where does this happen?

**Comment by racitup** [comment]
As it says at the top, the add to cart serializer has a hard-coded calculation whereas the modifiers are customisable. For example I have quantity discounts.

**Comment by jrief** [comment]
One of my customers uses per item discounts, they work together with a customized ``AddToCartSerializer``. This is how I do it:

```
class ExtraSerializer(serializers.Serializer):
    running_meters = serializers.FloatField(required=False, read_only=True)
    order_sample = serializers.BooleanField(label=_("Order a sample"), default=False,
                                            required=False)
    addable = serializers.BooleanField(default=True, read_only=True)
    availability = serializers.CharField(required=False, read_only=True)

    def __init__(self, instance=None, data=empty, **kwargs):
        # here I initialize the extra dict, which later is serialized into cart_item.extra
        super().__init(instance, data, **kwargs)

class AddToCartSerializer(BaseAddToCartSerializer):
    quantity = serializers.IntegerField(default=1, min_value=0)
    extra = ExtraSerializer()

    def get_instance(self, context, data, extra_args):
        # here in addition to the default get_instance, I manipulate the extra dict
        # compute per item quantity discounts, etc ...
        return {
            'product': product.id,
            'quantity': quantity,
            'unit_price': unit_price,
            'subtotal': subtotal,
            'extra': extra,
        }
```

Then, when iterating over the cart items, you can use the extra dict to compute per cart quantity discounts.

Something which would not work, is to run the cart modifiers while changing the quantity in the ``AddToCartSerializer``. This is because the item then is not yet in the cart.

**Comment by racitup** [comment]
Here's my generic solution:

```
class DummyItem(object):
    def __init__(self, **kwargs):
        self.__dict__.update(kwargs)


class AddToCartSerializer(AddToCartSerializerDefault):
    """
    Override the default product subtotal calculation to use the modifier pool
    """
    def __init__(self, instance=None, data=empty, **kwargs):
        context = kwargs.get('context', {})
        if 'request' in context and 'product' in context:
            instance = self.get_instance(context, data, kwargs)
            if data == empty:
                quantity = self.fields['quantity'].default
            else:
                quantity = self.fields['quantity'].to_internal_value(data['quantity'])
            instance.setdefault('quantity', quantity)
            # create a dummy cart item model object
            item_dict = {
                'product': context['product'],
                'cart': None,
                'extra': {},
                'extra_rows': {},
                'product_code': instance['product_code'],
                'quantity': instance['quantity'],
            }
            item = DummyItem(**item_dict)
            instance.setdefault('subtotal', self._modifier_linetotal(item, context['request']))
            # Skip immediate parent
            super(AddToCartSerializerDefault, self).__init__(instance, data, context=context)
        else:
            super(AddToCartSerializer, self).__init__(instance, data, **kwargs)

    def _modifier_linetotal(self, item, request):
        """Helper function to calculate item subtotal using cart modifiers"""
        for modifier in cart_modifiers_pool.get_all_modifiers():
            modifier.pre_process_cart_item(None, item, request)

        for modifier in cart_modifiers_pool.get_all_modifiers():
            modifier.process_cart_item(item, request)

        for modifier in cart_modifiers_pool.get_all_modifiers():
            modifier.post_process_cart_item(None, item, request)

        try:
            linetotal = item.extra_rows['currencycartmodifier'].instance['amount']
        except (KeyError, AttributeError):
            linetotal = item.line_total

        return linetotal
```
