### ISSUE TITLE
Customer orders list order date in wrong locale

### ISSUE THREAD

**Issue by racitup** [awesto/django-shop#630]
The javascript doesn't appear to put the order date in the correct locale.
From utils.js:
```
var timestamp = new Date(attrs.shopTimestamp);
element.html($filter('date')(timestamp, attrs.timeFormat));
```

Result in en locale:
![screen shot 2017-08-07 at 23 12 39](https://user-images.githubusercontent.com/18157195/29048018-78a2cd96-7bc6-11e7-9de8-4cf04b0318a8.png)

**Comment by jrief** [comment]
please check, if your have installed the correct ``angular-locale_XX.js``.
The problem is, that DRF returns the timestamp as isotimestamp which has to be converted on the client. This on the other side allows us to use libraries such as angular-timeago or ngtimeago.

**Comment by racitup** [comment]
Thanks for the tip! I fixed it with the following in the base template:

```
{% addtoblock "js" %}
  <script src="{% static 'node_modules/angular-i18n/angular-locale_'|add:LANGUAGE_CODE|add:'.js' %}"></script>
{% endaddtoblock %}
```

**Comment by jrief** [comment]
I will try to fix this with this https://github.com/jrief/django-angular/issues/305 issue.

**Comment by racitup** [comment]
I guess the advantage of the templatetag is it can check the existence of a file for each configured language 👍
