### ISSUE TITLE
CMS Pages?

### ISSUE THREAD

**Issue by rizplate** [awesto/django-shop#633]
Why is CMS Pages needed?

Can this thing run without django CMS?

**Comment by jrief** [comment]
Yes. Instead of creating a CMS page and using a CMS app, you can create the View directly, for instance such as:

```
class MyOrderView(order.OrderView):
    renderer_classes = (ShopTemplateHTMLRenderer, JSONRenderer, BrowsableAPIRenderer)
```

Note: the difference here is that you use the ``ShopTemplateHTMLRenderer`` instead of the ``CMSPageRenderer``.

Afterwards attach this view to your urls as:

```
    url(r'^order/$',
        MyOrderView.as_view(),
        name='shop-order'),

    url(r'^order/thanks-for-your-order/?$',
        MyOrderView.as_view(many=False, is_last=True),
        name='shop-order-last'),

    url(r'^order/(?P<slug>[\w-]+)/?$',
        MyOrderView.as_view(many=False),
        name='shop-order'),
```

**Comment by jrief** [comment]
@rizplate forgot to mention, that you should use the branch ``releases/0.11.x``.
