### ISSUE TITLE
javascript console errors for checkout auth forms on v0.11.dev0

### ISSUE THREAD

**Issue by racitup** [awesto/django-shop#638]
To reproduce, go to the cart when not logged in.
I'm pretty sure these weren't there for version 0.10.2.
The errors prevent the continue buttons from working.

> angular.min.js:14199 Error: Form has no \`name\`
>     at Object.link (http://127.0.0.1:8000/static/shop/js/auth.js:20:11)
>     at http://127.0.0.1:8000/static/node_modules/angular/angular.min.js:1259:18
>     at invokeLinkFn (http://127.0.0.1:8000/static/node_modules/angular/angular.min.js:10152:9)
>     at nodeLinkFn (http://127.0.0.1:8000/static/node_modules/angular/angular.min.js:9551:11)
>     at compositeLinkFn (http://127.0.0.1:8000/static/node_modules/angular/angular.min.js:8810:13)
>     at compositeLinkFn (http://127.0.0.1:8000/static/node_modules/angular/angular.min.js:8813:13)
>     at compositeLinkFn (http://127.0.0.1:8000/static/node_modules/angular/angular.min.js:8813:13)
>     at compositeLinkFn (http://127.0.0.1:8000/static/node_modules/angular/angular.min.js:8813:13)
>     at compositeLinkFn (http://127.0.0.1:8000/static/node_modules/angular/angular.min.js:8813:13)
>     at compositeLinkFn (http://127.0.0.1:8000/static/node_modules/angular/angular.min.js:8813:13) >    \<shop-auth-form ng-form="" name="login-reset_form" action="RELOAD_PAGE" role="form" class="ng-pristine ng-valid ng-scope"\>
> 
> angular.min.js:14199 Error: Form has no \`name\`
>     at Object.link (http://127.0.0.1:8000/static/shop/js/auth.js:20:11)
>     at http://127.0.0.1:8000/static/node_modules/angular/angular.min.js:1259:18
>     at invokeLinkFn (http://127.0.0.1:8000/static/node_modules/angular/angular.min.js:10152:9)
>     at nodeLinkFn (http://127.0.0.1:8000/static/node_modules/angular/angular.min.js:9551:11)
>     at compositeLinkFn (http://127.0.0.1:8000/static/node_modules/angular/angular.min.js:8810:13)
>     at compositeLinkFn (http://127.0.0.1:8000/static/node_modules/angular/angular.min.js:8813:13)
>     at compositeLinkFn (http://127.0.0.1:8000/static/node_modules/angular/angular.min.js:8813:13)
>     at compositeLinkFn (http://127.0.0.1:8000/static/node_modules/angular/angular.min.js:8813:13)
>     at compositeLinkFn (http://127.0.0.1:8000/static/node_modules/angular/angular.min.js:8813:13)
>     at compositeLinkFn (http://127.0.0.1:8000/static/node_modules/angular/angular.min.js:8813:13) >    \<shop-auth-form ng-form="" name="continue-as-guest_form" action="RELOAD_PAGE" role="form" class="ng-pristine ng-valid ng-scope">

**Comment by jrief** [comment]
Thanks for reporting.
