### ISSUE TITLE
ValueError with migration 0007_notification_recipient from tag 0.11

### ISSUE THREAD

**Issue by racitup** [awesto/django-shop#640]
I just got this error when migrating using the new release. I'm not sure where it's getting the '9' from, there's nothing in the shop_notification table with that number..

>   Applying shop.0007_notification_recipient...Traceback (most recent call last):
>   File "./manage.py", line 22, in <module>
>     execute_from_command_line(sys.argv)
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
>     utility.execute()
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
>     output = self.handle(*args, **options)
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 204, in handle
>     fake_initial=fake_initial,
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/db/migrations/executor.py", line 115, in migrate
>     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
>     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
>     state = migration.apply(state, schema_editor)
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/db/migrations/migration.py", line 129, in apply
>     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/db/migrations/operations/special.py", line 189, in database_forwards
>     self.code(from_state.apps, schema_editor)
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/shop/migrations/0007_notification_recipient.py", line 16, in forwards
>     for row in Notification.objects.all():
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/db/models/query.py", line 256, in __iter__
>     self._fetch_all()
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/db/models/query.py", line 1087, in _fetch_all
>     self._result_cache = list(self.iterator())
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/db/models/query.py", line 65, in __iter__
>     for row in compiler.results_iter(results):
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 795, in results_iter
>     row = self.apply_converters(row, converters)
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 779, in apply_converters
>     value = converter(value, expression, self.connection, self.query.context)
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/shop/models/fields.py", line 95, in from_db_value
>     return self.enum_type(value)
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/shop/models/fields.py", line 49, in __call__
>     return super(ChoiceEnumMeta, cls).__call__(value, *args, **kwargs)
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/enum.py", line 241, in __call__
>     return cls.__new__(cls, value)
>   File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/enum.py", line 476, in __new__
>     raise ValueError("%r is not a valid %s" % (value, cls.__name__))
> ValueError: 9 is not a valid ChoiceEnum

**Comment by jrief** [comment]
Confirmed. I have to check this.

**Comment by racitup** [comment]
I thought adding `enum_type=Notify` to the migration below would fix it, but no luck. The '9' appears to come from `default=Notify.NOBODY`.
```
migrations.AddField(
    model_name='notification',
    name='notify',
    field=shop.models.fields.ChoiceEnumField(
        verbose_name='Whom to notify',
        default=Notify.NOBODY,
        enum_type=Notify),
),
```

**Comment by jrief** [comment]
sorry for that, I tested this but made a small change later, which apparently caused your problem.
For now it seems to be fixed, but maybe I can find a cleaner solution.
