### ISSUE TITLE
Order thank you page changed from 0.10.2 in 0.11

### ISSUE THREAD

**Issue by mliudev** [awesto/django-shop#646]
We've recently upgraded to django-shop 0.11 which caused some of our checkout tests to fail because the expected "Thank you page" no longer exists. After doing some debugging I think the actual bug is in 0.10.2 but was fixed by the order plugin refactoring in 0.11.

In 0.10.2 the thank you page would show the Order list view instead of the detail view. This is confusing because the url here in order_last.py indicates that 'many' should be False: https://github.com/awesto/django-shop/blob/0.10.2/shop/urls/order_last.py#L8. However 'many' is always true when the code reaches the 'OrderView' and so the thank you page shows the list view.

![screen shot 2017-08-30 at 12 28 59 pm](https://user-images.githubusercontent.com/11674155/29883597-d40b4cfc-8d7e-11e7-92dd-f6ca94a6547b.png)

You can also verify this by using debug statements within the OrderView.

In 0.11 the thank you page is correct according to the code and show the order detail page, but there is no thank you message. 

![screen shot 2017-08-30 at 12 27 51 pm](https://user-images.githubusercontent.com/11674155/29883564-bb364786-8d7e-11e7-807f-f014d5ef2969.png)

There are a couple questions that I have regarding this behavior. What is the intended thank you page? Should that page show the thank you message?

**Comment by jrief** [comment]
In our current setups, the thank-you page is the last Order Detail View for the current customer. You can check this on the last demos. Otherwise that's a serious bug, however I would have noticed it before releasing 0.11.

What changed in 0.11 is that you can also hard-code the View using a page routed by Djangos `urls.py` rather than the internal CMS URL router.

So, please provide me, which routing technique you are using and how you resolve the Order Detail View.

**Comment by jrief** [comment]
In 0.11, the Order CMS App routes directly onto the Order View, and without requiring `shop/urls/order.py`. Please check the corresponding code over there.

**Comment by mliudev** [comment]
This turned out to be an issue with our custom code. We weren't inheriting from OrderCMSApp like I thought we were, instead we were simply subclassing CMSApp and using 'shop.urls.order' which defaults to `many=true`. I'll go ahead and close this.
