### ISSUE TITLE
Feature suggestion: customer form for managing addresses

### ISSUE THREAD

**Issue by racitup** [awesto/django-shop#647]
In the UK we have The Data Protection Act 1998 which forces certain controls on user data. Two of these are:

> A Right of Subject Access
> A data subject (a customer) has a right to be supplied by a data controller (in this case the company that runs the shop) with the personal data held about him or her. The data controller can charge for this (usually around £10 pounds).
> 
> A Right of Correction
> A data subject may force a data controller to correct any mistakes in the data held about them.

For anyone managing a shop it is clearly easier to pass these requirements back to the customer by:
1. giving the customer access to **all** of the information you hold about them directly
2. allow them to correct their own information

It seems that the only thing missing from the shop at the moment is the ability to view/manage billing and shipping addresses.

There is also a 'Right to erasure' which would be a button for the removal of a customer account. This would not need to remove order, delivery and payment history that might be required for accounting, etc, just the cart, customer and address entries for a customer.

Presumably other countries have similar laws?

**Comment by jrief** [comment]
> It seems that the only thing missing from the shop at the moment is the ability to view/manage billing and shipping addresses.

If you examine the demo shop, the customer can actually edit and modify his shipping and billing addresses. He can even add different addresses if  the merchant allows to do so.

However it is not possible to change an address for an order after it has been fulfilled. This is to keep integrity. Does UK law require to change that for fulfilled orders? That imo would be really dangerous!

**Comment by racitup** [comment]
I've run the latest demo again and can't find a page dedicated to the addresses, do you mean in the checkout? I was thinking of another page like the "Your Personal Details" page..

No, keeping personal details static as part of an order is fine and a great idea. Once an order is submitted it becomes a contract and part of accounting records, etc, so it becomes necessary to have other controls on that data for the business to function properly. The customer still needs to have access to it, but read-only is fine.

**Comment by jrief** [comment]
>  I was thinking of another page like the "Your Personal Details" page..

Ah, got it! Yes this would be perfectly possible, since the address(es) is/are bound to the Customer model. 

You can presumably create your own page and add this Address Form Plugin.

**Comment by racitup** [comment]
Yes that's the idea, though I can't find an Address Form Plugin?

**Comment by jrief** [comment]
By replacing your Personal Details page with the content of this placeholder https://dpaste.de/o9MC , you should be able to edit the customer addresses outside of the checkout page.

**Comment by racitup** [comment]
This is great, thanks!
For anyone else, you can add the `Checkout Address Form` plugins to the `customer.is_registered` section of the personal details page.
