### ISSUE TITLE
Missing migration

### ISSUE THREAD

**Issue by amadornimbis** [awesto/django-shop#649]
You can verify there is a missing migration (number 0008) if you clone the repository, install the requirements, and from the example directory run `python manage.py makemigrations --dry-run`
```
Migrations for 'shop':
  /Users/eric/nimbis/django-shop/shop/migrations/0008_auto_20170909_0328.py:
    - Alter field notify on notification
    - Alter field recipient on notification
```

**Comment by jrief** [comment]
Thanks for reporting.

It actually doesn't do any harm, but I will add the missing migration on version 0.11.1
