### ISSUE TITLE
deploy

### ISSUE THREAD

**Issue by helvrud** [awesto/django-shop#659]
I was following the tutorial http://django-shop.readthedocs.io/en/latest/tutorial/intro.html
I went up to the point 
_export DJANGO_SHOP_TUTORIAL=i18n_polymorphic DJANGO_DEBUG=1_
_./manage.py initialize_shop_demo_
_./manage.py runserver_
And it works well while I use the development server
but when i run the same using uwsgi
_uwsgi --http :8000 --wsgi-file wsgi.py_ 
it does not find static files and gives a lot of Not Found warnings
for instance **WARNING: Not Found: /en/static/myshop/js/navbar.js/**
As a result the web site looks ugly.
Sorry if the issue is stupid.

**Comment by jrief** [comment]
well, this actually is expected behaviour in Django. Before deploying to a production site, you have to invoke ``./manage.py collectstatic``. Since django-SHOP uses django-sass-processors, invoke ``./manage.py compilescss`` beforehand.

**Comment by helvrud** [comment]
That would be too easy solution. Anyway thank you for _compilescss_...
I do the following (from the tutorial)
_virtualenv -p $(which python3) env 
. env/bin/activate
pip install -U pip setuptools
git clone --depth 1 https://github.com/awesto/django-shop
cd django-shop
pip install -r requirements/common.txt
pip install --no-deps -e .
pip install 'Django<1.11'
cd example
npm install
export DJANGO_SHOP_TUTORIAL=i18n_polymorphic DJANGO_DEBUG=1
./manage.py initialize_shop_demo
./manage.py runserver
./manage.py compilescss 
./manage.py collectstatic
uwsgi --http :8000 --module wsgi_

And the server complains that it can not find the static files, despite, that these are in STATIC_ROOT

with best regards, Oleg

**Comment by jrief** [comment]
Hi Oleg,
did you configure your uwsgi daemon to serve static files?

This for instance is the uwsgi.ini file from django-SHOP's Docker setup:
```
[uwsgi]
plugins = python3, logfile
chdir = /web/demo-shop
umask = 002
http-socket = :9001
env = DJANGO_WORKDIR=/web/workdir
env = DJANGO_SETTINGS_MODULE=myshop.settings
exec-pre-app = /web/demo-shop/manage.py initialize_shop_demo --noinput
module = wsgi:application
buffer-size = 32768
static-map = /static=/web/workdir/static
static-map = /media=/web/workdir/$(DJANGO_SHOP_TUTORIAL)/media
post-buffering = 1
processes = 1
threads = 1
logger = file:/web/logs/shop.log
```
