### ISSUE TITLE
email_auth 0004_auto_20170411_1733.py migration not matching model on py3

### ISSUE THREAD

**Issue by racitup** [awesto/django-shop#665]
The django AbstractUser upon which email_auth is based determines the username validator like this:

`username_validator = UnicodeUsernameValidator() if six.PY3 else ASCIIUsernameValidator()`

Whereas the above migration fixes it to `ASCIIUsernameValidator()`. So on python3 a new migration is made.

Fixed [here](https://github.com/racitup/django-shop/blob/dyn_pay_modifiers_0111/email_auth/migrations/0004_auto_20170411_1733.py) by copying the django migration but no idea how this affects django <1.10.

**Comment by jrief** [comment]
just integrated your patch into the current version.
