### ISSUE TITLE
django-shop/email_auth/migrations/0005_auto_20171101_1035.py is missing

### ISSUE THREAD

**Issue by gntjou** [awesto/django-shop#676]
When I  execute python manage.py makemigrations --dry-run, I got the message:
Migrations for 'email_auth':
  /home/frank/webshop/django-shop/email_auth/migrations/0005_auto_20171101_1035.py:
    - Alter field username on user

In the directory there is not such a file.

Where can I find the file 0005_auto_20171101_1035.py

**Comment by jrief** [comment]
That file should not exist. Presumable it has been added by a previous ``makemigrations`` command. Try to locate that string and remove it from the offending migration file.

**Comment by gntjou** [comment]
Solved, Thx
