### ISSUE TITLE
Plugin left_extension is missing

### ISSUE THREAD

**Issue by gntjou** [awesto/django-shop#682]
After an error/warningless installation of django-Shop, choosing i18n_commodity and creating the approriate pages, I get the following error after clicking on the cart icon:
TemplateSyntaxError at /en/cart/
Plugin is missing
Error during template rendering
In template /home/frank/test/django-shop/example/myshop/templates/myshop/cart/editable.html, error at line 0

Exactly the same error occurs when installing the i18n_commodity demo with initialize_shop_demo.

A slightly different error occurs after installing i18n_polymorphic and clicking on view orders in the footer.

As far as i have been able to trace back they are all related to a missing plugin left_extension.

**Comment by jrief** [comment]
Thanks for reporting.
Indeed, there have been some changes in the Left-/Right PluginExtensions. Please use ``./manage.py cms delete-orphaned-plugins`` to remove these plugins temporarily for now.

**Comment by gntjou** [comment]
Thanks for your reply.
I've tried your solution in all three cases, but  it didn't solve the issue in either case.

**Comment by jrief** [comment]
The current master branch should have a fix for it. Please retry.
