### ISSUE TITLE
Fix #683 not working

### ISSUE THREAD

**Issue by gntjou** [awesto/django-shop#685]
The Fix: In plugin child_plugin_instances may be None #683 didn't solve either problem mentioned in issue #682.

I checked the fix with a fresh installation of the i18n_commodity demo as well as the i18n_polymorphic demo.

**Comment by jrief** [comment]
which commit hash?

**Comment by gntjou** [comment]
e615cda9384721d08b4658673dd2df7b6cd91710 Merge pull request #683 from awesto/releases/0.11.x

I still get the error messages 'plugin missing'. They are related to the parents ShopOrderViewsPlugin and ShopCartPlugin

**Comment by gntjou** [comment]
Solved with commit ed9144dc98a7cb7e72d4af8005417a176b11a129
