### ISSUE TITLE
No relation between cms_pages and CatalogListView

### ISSUE THREAD

**Issue by gntjou** [awesto/django-shop#691]
The cms_pages many-to-many relation in the commodity is not influencing the CatalogListView. Regardless of the relation made in the admin interface, every commodity shows on every cms_page.

**Comment by jrief** [comment]
You must either use the `CMSPageCatalogWrapper` or apply the filter `CMSPagesFilterBackend` on the CatalogListView. This filter does the job.

**Comment by gntjou** [comment]
Thanx, using CMSPageCatalogWrapper in i18n_commodities.py did the job.

**Comment by MikhailNatalenko** [comment]
It seems, i faced with same issue. Could you help me to solve it? I don't understand, how to use this wrapper @gntjou @jrief

**Comment by MikhailNatalenko** [comment]
Oh, i got it. `CMSPageCatalogWrapper`  uses instead of `ProductListView` and `CatalogSearchSerializer` instead of `ProductSummarySerializer` lucky i found this issue.
