### ISSUE TITLE
Getting this error while running example app

### ISSUE THREAD

**Issue by selvailm** [awesto/django-shop#696]
File to import not found or unreadable: shope/css/django-shop.
       Parent style sheet: E:/django-shop/example/myshop/static/myshop/css/default.scss

**Comment by jrief** [comment]
This is related to django-sass-processor. Please check to docs there and/or explain how to reproduce it.

**Comment by selvailm** [comment]
Thank you for reply,
I am new to django shop and 
I followed the steps from http://django-shop.readthedocs.io/en/latest/tutorial/intro.html
After Populating the Database using Fixtures .I started server and server running fine. 
When i created new page using django cms and when i go to link http://127.0.0.1:8000
I got the above error 



Request Method: | GET
-- | --
http://127.0.0.1:8000/en/
1.10.2
CompileError
Error: File to import not found or unreadable: shop/css/django-shop.  Parent style sheet: E:/demo/Tutorial/django-shop/example/myshop/static/myshop/css/default.scss         on line 1 of myshop/static/myshop/css/default.scss >> @import "shop/css/django-shop";    ^

**Comment by jrief** [comment]
it seems as if you're running django-SHOP on Windows. Please retry using Docker, there these problem should not occur.
