### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by jainaman224** [awesto/django-shop#713]
I think we should add `django_select2`, `django-angular` and `djangoshop_stripe` to the requirements/common.txt file. I have to install it manually.

**Comment by rfleschenberg** [comment]
Sounds right. Want to send a PR?

**Comment by Aiky30** [comment]
@jainaman224 were you upgrading from an earlier version of Django shop? I ask because the setup.py file of Django shop has those packages listed as required and pip would automatically install them when installing Django shop. This assumes you're using pip.

It is still valid that the packages should also be listed in the requirements files because they are for us developers.

**Comment by jainaman224** [comment]
No, I am using this version of Django-shop. It gives me error.

**Comment by Aiky30** [comment]
@jainaman224 That is odd. I have installed the current version 11.7 a few times without any errors. Did you follow the manual installation process or via docker?  

Manual installation: [http://django-shop.readthedocs.io/en/latest/tutorial/intro.html](http://django-shop.readthedocs.io/en/latest/tutorial/intro.html )

**Comment by rfleschenberg** [comment]
@jainaman224 Did you install `common.txt`? I think you should install, for example, `django110.txt`, which includes these packages.

Does that work?

Do we have any documentation anywhere that tells people to use `common.txt`?

**Comment by Aiky30** [comment]
@jainaman224 There is documentation for the common.txt in the link that I included above but not for any existing install where an old version of Django is present which would require the specific version of the select2 and angular packages (django19.txt, django110.txt, django11.txt).

**Comment by jainaman224** [comment]
I am closing my PR and this issue. Updation in documents will be better instead.
