### ISSUE TITLE
Failed building wheel for rcssmin

### ISSUE THREAD

**Issue by suthargk** [awesto/django-shop#719]
----------------------------------------
  Failed building wheel for hiredis
  Running setup.py clean for hiredis
  Running setup.py bdist_wheel for rcssmin ... error
  Complete output from command /home/c013ra/Desktop/django-shop/myenv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-24x5vmdv/rcssmin/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-ip9ie3jm --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  copying ./rcssmin.py -> build/lib.linux-x86_64-3.5
  running build_ext
  building '_rcssmin' extension
  creating build/temp.linux-x86_64-3.5
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DEXT_MODULE=_rcssmin -UEXT_PACKAGE -I_setup/include -I/usr/include/python3.5m -I/home/c013ra/Desktop/django-shop/myenv/include/python3.5m -c rcssmin.c -o build/temp.linux-x86_64-3.5/rcssmin.o
  In file included from rcssmin.c:18:0:
  _setup/include/cext.h:34:20: fatal error: Python.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for rcssmin
  Running setup.py clean for rcssmin
  Running setup.py bdist_wheel for rjsmin ... error
  Complete output from command /home/c013ra/Desktop/django-shop/myenv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-24x5vmdv/rjsmin/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-fe4qkzhn --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  copying ./rjsmin.py -> build/lib.linux-x86_64-3.5
  running build_ext
  building '_rjsmin' extension
  creating build/temp.linux-x86_64-3.5
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DEXT_MODULE=_rjsmin -UEXT_PACKAGE -I_setup/include -I/usr/include/python3.5m -I/home/c013ra/Desktop/django-shop/myenv/include/python3.5m -c rjsmin.c -o build/temp.linux-x86_64-3.5/rjsmin.o
  In file included from rjsmin.c:18:0:
  _setup/include/cext.h:34:20: fatal error: Python.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for rjsmin
  Running setup.py clean for rjsmin
Failed to build hiredis rcssmin rjsmin
django-filer 1.3.0 has requirement easy-thumbnails<2.5,>=2, but you'll have easy-thumbnails 2.5 which is incompatible.
django-haystack 2.5.0 has requirement Django<1.10, but you'll have django 1.10 which is incompatible.
django-allauth 0.35.0 has requirement Django>=1.11, but you'll have django 1.10 which is incompatible.
Installing collected packages: rcssmin, rjsmin, django-compressor, Unidecode, django-polymorphic, olefile, Pillow, easy-thumbnails, django-mptt, django-filer, django-filter, django-fsm, django-fsm-admin, django-haystack, django-ipware, django-parler, jsonfield, django-post-office, redis, django-redis-cache, django-redis-sessions, djangorestframework, six, django-rest-auth, django-sass-processor, djangocms-bootstrap3, html5lib, djangocms-text-ckeditor, djangocms-cascade, python-dateutil, drf-haystack, elasticsearch, hiredis, libsass, python-openid, pytz, virtualenv, wheel, beautifulsoup4, bs4
  Running setup.py install for rcssmin ... error
    Complete output from command /home/c013ra/Desktop/django-shop/myenv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-24x5vmdv/rcssmin/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-y8abyajq/install-record.txt --single-version-externally-managed --compile --install-headers /home/c013ra/Desktop/django-shop/myenv/include/site/python3.5/rcssmin:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    copying ./rcssmin.py -> build/lib.linux-x86_64-3.5
    running build_ext
    building '_rcssmin' extension
    creating build/temp.linux-x86_64-3.5
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DEXT_MODULE=_rcssmin -UEXT_PACKAGE -I_setup/include -I/usr/include/python3.5m -I/home/c013ra/Desktop/django-shop/myenv/include/python3.5m -c rcssmin.c -o build/temp.linux-x86_64-3.5/rcssmin.o
    In file included from rcssmin.c:18:0:
    _setup/include/cext.h:34:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/c013ra/Desktop/django-shop/myenv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-24x5vmdv/rcssmin/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-y8abyajq/install-record.txt --single-version-externally-managed --compile --install-headers /home/c013ra/Desktop/django-shop/myenv/include/site/python3.5/rcssmin" failed with error code 1 in /tmp/pip-install-24x5vmdv/rcssmin/

**Comment by haricot** [comment]
i do not know if it helps but it looks like this issue https://github.com/overshard/timestrap/issues/15

**Comment by jrief** [comment]
@suthargk Please don't post long listing of build errors, since they are specific to your projects setup. If unsure, use the prepared Docker container, there everything works.

**Comment by mdnur89** [comment]
Encountered the same problem when using pip install but I use anaconda cloud and those packages that fail with pip work with conda install given the package is available in the repo's
