### ISSUE TITLE
change the image in product admin do not update the thumbnails CatalogListPlugin

### ISSUE THREAD

**Issue by haricot** [awesto/django-shop#722]
I tried with several version and docker image, thumbnails do not update.
The thumbnails is updated only if the server is restarted or reloded.

![peek 13-04-2018 11-02-b](https://user-images.githubusercontent.com/344493/38730256-09b98672-3f16-11e8-8a51-11dd955289ef.gif)

I try to investigate without success, any track would be welcome.

**Comment by haricot** [comment]
Thanks for the clue. Effectively, if we change the cache parameter temporarily, it works.
It must be a problem with the redis setting or logic, it's the same problem with docker-compose.


```
CACHES = {                                                                                                           
    'default': {                                                                                                     
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',                                                    
    }                                                                                                                
} 
```

**Comment by jrief** [comment]
There is a special admin mixin to invalidate the cache whenever we save the product. It's named `InvalidateProductCacheMixin ` and I have seen, that it currently is not added to `myshop.admin.i18n_polymorphic. SmartCardAdmin`. I tried ti do that, but still get an old version of the `<figure>...` template. I have to investigate further on this.

Caching the figures in the catalog's list view has a quite dramatic speed influence.

**Comment by haricot** [comment]
I do not know if this is binding, but by doing this manipulation: I get this error: 
![peek 15-04-2018 14-02](https://user-images.githubusercontent.com/344493/38778215-20e0a096-40b6-11e8-82f2-f7e88f6d078f.gif)

```
MultiValueDictKeyError at /admin/myshop/smartcard/5/change/

"'productimage_set-0-id'"

Request Method: 	POST
Request URL: 	http://127.0.0.1:8000/admin/myshop/smartcard/5/change/?language=en&cms_path=%2Fshop%2Fsmartcards%2Fsdxc-card-64gb
Django Version: 	1.10.8
Exception Type: 	MultiValueDictKeyError
Exception Value: 	

"'productimage_set-0-id'"

Exception Location: 	/home/path/sources/testshop/Tutorial/shoptutorial/lib/python3.6/site-packages/django/utils/datastructures.py in __getitem__, line 85
Python Executable: 	/home/path/sources/testshop/Tutorial/shoptutorial/bin/python
Python Version: 	3.6.4
Python Path: 	

['/home/path/sources/testshop/Tutorial/django-shop/example',
 '/home/path/sources/testshop/Tutorial/shoptutorial/lib/python36.zip',
 '/home/path/sources/testshop/Tutorial/shoptutorial/lib/python3.6',
 '/home/path/sources/testshop/Tutorial/shoptutorial/lib/python3.6/lib-dynload',
 '/usr/lib64/python3.6',
 '/usr/lib/python3.6',
 '/home/path/sources/testshop/Tutorial/shoptutorial/lib/python3.6/site-packages',
 '/home/path/sources/testshop/Tutorial/django-shop']

Server time: 	Sun, 15 Apr 2018 14:02:40 +0200
```
(It may be normal since the previous one no longer exists)

**Comment by haricot** [comment]
By keeping `InvalidateProductCacheMixin` at the beginning it works. #730
Thanks for the indication !
