### ISSUE TITLE
Issue when USE_TOUSAND_SEPARATOR set to True.

### ISSUE THREAD

**Issue by dinoperovic** [awesto/django-shop#724]
Hi,

I've encountered an issue when setting `USE_TOUSAND_SEPARATOR = True`.

This is the result in admin, as well as in other places where Order is displayed:

![screen shot 2018-04-23 at 14 17 29](https://user-images.githubusercontent.com/1486159/39126133-b3178082-4701-11e8-898b-0e7f7e4f1888.png)

This issue only appear in the order totals. Order items, and Cart is displayed in a correct format.

I am using version 0.12 of django-shop.

**Comment by jrief** [comment]
Thanks for reporting.
For a fast evaluation, please check latest commit on branch `releases/0.12.x`.

**Comment by dinoperovic** [comment]
@jrief 

This fixed the rendering in order admin, however the issue still remains in other places where order totals are displayed. Note in screenshot, the order's extra fields (promo) renders like it should.

![screen shot 2018-04-23 at 15 55 10](https://user-images.githubusercontent.com/1486159/39131087-e51704ba-470e-11e8-89e3-ea5cf9ac08e5.png)

**Comment by jrief** [comment]
fixed that too.

In case you stumble upon this issue again, in order to correctly format an amount of type `MoneyInHRK`, wrap it into `str(amount)`. This should handle the thousand separator and the decimal dot in the current locale.

**Comment by dinoperovic** [comment]
@jrief got it, thanks!
