### ISSUE TITLE
what are the actuall requirements for your example shop? 

### ISSUE THREAD

**Issue by Revel109** [awesto/django-shop#728]
I am in the directory: ~/Tutorial/django-shop/example$ 
when I am going to: pip3 install -r requirements.txt, I got some version complexity. It shows me some errors like: django-shop 0.12.1 has requirement Django<2.0,>=1.9.12, but you'll have django 1.9 which is incompatible.
django-allauth 0.35.0 has requirement Django>=1.11, but you'll have django 1.9 which is incompatible.

So, I'm getting bored actually.and wanna really know what are the actual requirements? 

N.B:I did this before: 
(myenv)$ cd django-shop
(myenv)$ pip install -e .

**Comment by jrief** [comment]
Thanks for reporting.
Django-SHOP version 0.12 requires Django-1.10 as its minimum required version, but Django-1.11 is recommended.
