### ISSUE TITLE
Issue with Notification admin transition choices (RETURN_VALUE).

### ISSUE THREAD

**Issue by dinoperovic** [awesto/django-shop#729]
Hi.

Order transitions that use `RETURN_VALUE` as target don't display in `transition_choices` in Notification admin. 

I would expect "Refund payment" and "Order Canceled" to be in choices from `CancelOrderWorkflowMixin` transitions, instead I get this: 

![screen shot 2018-05-04 at 11 24 20](https://user-images.githubusercontent.com/1486159/39621641-c52e071e-4f8f-11e8-9504-c82e069d5920.png)

There's two *RETURN_VALUE* choices since I use `ManualPaymentWorkflowMixin` as well.
("Dostava" and "Paid using WSPay" are my custom ones.)

**Comment by jrief** [comment]
Thanks for reporting. This indeed seems to be a bug.

**Comment by jrief** [comment]
Please recheck with the latest HEAD from master. If everything is OK, I'll release 0.12.2

**Comment by dinoperovic** [comment]
@jrief It works with the latest HEAD. Thanks!

**Comment by dinoperovic** [comment]
Hi @jrief.

Is the version `0.12.2` going to be released with this fix anytime soon?
I still have it installed via github directly.

Thanks.
