### ISSUE TITLE
ImportError: No module named 'polymorphic.manager'

### ISSUE THREAD

**Issue by dismine** [awesto/django-shop#732]
Hi,

Today i got import error: File "/home/.../shop/models/product.py", line 12, in <module>
    from polymorphic.manager import PolymorphicManager

I installed _django-polymorphic==2.0.2_

It seems this issue related to [django-polymorphic's issue](https://github.com/django-polymorphic/django-polymorphic-tree/issues/61). [Patch](https://github.com/django-polymorphic/django-polymorphic-tree/pull/62/files) from there also works in my case.

**Comment by dismine** [comment]
Hi,

Can someone fix this issue?

**Comment by haricot** [comment]
@dismine 
with django-polymorphic==2.0.2 import manager takes a s
`
from polymorphic.managers import PolymorphicManager`

**Comment by dismine** [comment]
I know. I mean i just test issue #735 and shop/models/product.py in branch [releases/0.12.x](https://github.com/awesto/django-shop/commits/releases/0.12.x) still has string `from polymorphic.manager import PolymorphicManager`. If a maintainer is busy i can create a pull request. I just don't know which branch to use.

**Comment by haricot** [comment]
django-110 need django-polymorphic==1.3 so in version django-shop 0.12.x  you have to use this for the moment.
does this pose a problem?

**Comment by dismine** [comment]
We just could add
```
try: 
    from polymorphic.managers import PolymorphicManager
except ImportError:
    from polymorphic.manager import PolymorphicManager
```

and totally forget about this issue.

> does this pose a problem?

Yes, thank you. We can close this issue.

**Comment by haricot** [comment]
it's planned for the future version:
https://github.com/awesto/django-shop/pull/723/files#diff-794ded6023e23e60359c61837f571483R16
