### ISSUE TITLE
Dropdown navigation menu, when in mobile client

### ISSUE THREAD

**Issue by markusmo** [awesto/django-shop#743]
Hi
I followed the tutorial for django-SHOP for installation and its working just fine.
As I wanted to try out the navigation menu, when its collapsed, such as in a mobile client, the tapping/clicking event does not expand the navigation menu. The CSS class `collapse` always states `display:none;`
I checked all the dependencies, such as angular.min.js, angular-animate.min.js and ui-bootstrap-tpls.js and it is all there and loaded...
The event triggers, but then the CSS does not change.

A screenshot of the libraries, rendered for the site:
![grafik](https://user-images.githubusercontent.com/1172204/42692203-246dd554-86ab-11e8-90ab-c8c04867c6d7.png)

I am quite confused, why it does not work, as in all the examples I found, it looks exactly the same.

**Comment by jrief** [comment]
Confirmed.
I'm currently checking why this happens. Presumably an AngularJS directive hides the scope.

**Comment by jrief** [comment]
@markusmo Please retry with the latest HEAD from https://github.com/jrief/djangocms-bootstrap3
If that works for you, I'll bundle a new version on PyPI.

**Comment by markusmo** [comment]
Works like a charm :-)
Thanks a lot for the help.

**Comment by jrief** [comment]
Just released djangocms-bootstrap3 version 0.4
