### ISSUE TITLE
Support for multiple CatalogListCMSApp instances

### ISSUE THREAD

**Issue by dismine** [awesto/django-shop#748]
Hi,

I have a configuration with two products. These two products should be separated for this reason i have made two instances of `CatalogListCMSApp`. It seems django CMS supports this behavior. I can connect pages to applications. But i have different situation in admin page. I see pages as categories only for the first `CatalogListCMSApp` instance that appears in file `cms_apps.py`. Is there is way to show all pages related to `CatalogListCMSApp`? As i assume `CMSPageAsCategoryMixin` is responsible for this.

I just want to hear thoughts from developers to plan my next steps.

**Comment by dismine** [comment]
I have found a way to "improve" `CMSPageAsCategoryMixin`

First change to _find_catalog_list_apphook():

```python
def _find_catalog_list_apphook():
    from shop.cms_apphooks import CatalogListCMSApp
    from cms.apphook_pool import apphook_pool

    apphooks = []
    for name, app in apphook_pool.apps.items():
        if isinstance(app, CatalogListCMSApp):
            apphooks.append(name)
    if apphooks:
        return apphooks
    else:
        raise ImproperlyConfigured("You must register a CMS apphook of type `CatalogListCMSApp`.")
```
Then change for `CMSPageAsCategoryMixin`:
```python
class CMSPageAsCategoryMixin(object):
...
    def formfield_for_manytomany(self, db_field, request, **kwargs):
        if db_field.name == 'cms_pages':
            limit_to = []
            cmsapp_list = _find_catalog_list_apphook()
            for apphook in cmsapp_list:
                limit_to.append(getattr(self, 'limit_to_cmsapp', apphook))

            # restrict many-to-many field for cms_pages to ProductApp only
            limit_choices_to = {
                'publisher_is_draft': False,
                'application_urls__in': limit_to,
            }

            queryset = Page.objects.filter(**limit_choices_to)
            widget = admin.widgets.FilteredSelectMultiple(_("CMS Pages"), False)
            required = not db_field.blank
            field = CategoryModelMultipleChoiceField(queryset=queryset, widget=widget, required=required)
            return field
        return super(CMSPageAsCategoryMixin, self).formfield_for_manytomany(db_field, request, **kwargs)
```

What do you think?

**Comment by dismine** [comment]
Can somebody comment my idea?

**Comment by jrief** [comment]
`CMSPageAsCategoryMixin` is only used to extend the django admin for products belonging to a category, which is a django-CMS page.
I actually don't understand your question.

**Comment by dismine** [comment]
Okay. As i said i have currently two types of products. But i don't want to see them in one hierarchy. For example, i have 'pattern' and 'book'. Instead of showing all in one view list mixed i want two separate lists. To achieve this i can create root category 'Products' or define several apphooks inherited from `CatalogListCMSApp`. Several apphooks approach works. But in django admin, when i create new product i cannot set correct category because current implementation always return first instance of `CatalogListCMSApp` in list. Where i need all of them to select correct category. 

Having two apphooks allow me to avoid creating common root CMS page.

**Comment by jrief** [comment]
In Django's admin list view, you get a list of all products, independently of their category.
Then, by using `CMSPageAsCategoryMixin` in the ProductAdmin-class, you get an additional ManyToMany-select box. There you can choose zero to many CMS pages, which shall act as category roots.
Note that only pages marked as "Catalog List" are eligible to be selected.

**Comment by dismine** [comment]
Yes, you are right. I totally understand this.

> Note that only pages marked as "Catalog List" are eligible to be selected.

If i have several `CatalogListCMSApp` apphook instances (different classes, not different names for the same class) i will see pages only related to first defined class in file `cms_apps.py`. Where i want `CMSPageAsCategoryMixin` not to stop and show me pages from all `CatalogListCMSApp` apphook classes.

**Comment by dismine** [comment]
```python
class CatalogPatternListApp(CatalogListCMSApp):
    name = _("Catalog Pattern List")
    app_name = "catalog_pattern_list"

    def get_urls(self, page=None, language=None, **kwargs):
        return [
            url(r'^$', ProductListView.as_view(serializer_class=ProductSummarySerializer,
                                               redirect_to_lonely_product=True),
                name='product_list'),
            url(r'^(?P<slug>[\w-]+)/add-pattern-to-cart/$',
                AddToCartView.as_view(serializer_class=AddProductToCartSerializer, lookup_field='translations__slug'),
                name='add_pattern_to_cart'),
            url(r'^(?P<path>[\w-]+)/(?P<slug>[\w-]+)/?$',
                PShopProductRetrieveView.as_view(serializer_class=ProductDetailSerializer,
                                                 lookup_field='translations__slug'), name='product_detail'),

        ]


apphook_pool.register(CatalogPatternListApp)


class CatalogBookListApp(CatalogListCMSApp):
    name = _("Catalog Book List")
    app_name = "catalog_book_list"

    def get_urls(self, page=None, language=None, **kwargs):
        return [
            url(r'^$', ProductListView.as_view(serializer_class=ProductSummarySerializer,
                                               # redirect_to_lonely_product=True
                                               ), name='book_product_list'),
            url(r'^(?P<slug>[\w-]+)/add-book-to-cart/$',
                AddToCartView.as_view(serializer_class=AddProductToCartSerializer, lookup_field='translations__slug'),
                name='add_pattern_to_cart'),
            url(r'^(?P<path>[\w-]+)/(?P<slug>[\w-]+)/?$',
                PShopProductRetrieveView.as_view(serializer_class=ProductDetailSerializer,
                                                 lookup_field='translations__slug'), name='book_detail'),

        ]


apphook_pool.register(CatalogBookListApp)
```

**Comment by dismine** [comment]
> does this work for you?

Yes.

> Did you assign that App to your CMS page in their advanced settings?

Yes. But i don't see related to CatalogBookListApp pages in admin site because it defined second in the list. Only pages related CatalogPatternListApp. Except for this all is fine.

My fix for CMSPageAsCategoryMixin fix this. And i published my change. Can you look at it and add to upstream?

**Comment by dismine** [comment]
@jrief thank you for your help! But i still cannot realize all i want in one `CatalogListCMSApp`. But i have found solution. I just inherited from `CMSPageAsCategoryMixin` and extended it with my changes to support many instances.
