### ISSUE TITLE
Dropdown in the menu not expanding

### ISSUE THREAD

**Issue by markusmo** [awesto/django-shop#749]
Hi
I encountered the issue, while programming, that my dropdown menu in the shop (see picture):
![grafik](https://user-images.githubusercontent.com/1172204/45295363-b8cdfb80-b4fe-11e8-8fd3-e40001ab0737.png)
is not expanding, showing my categories.
When navigating to a product, the breadcrumb shows the right path, and clicking the subcategory(page) of "shop" is also showing me the right products of the corresponding category:
![grafik](https://user-images.githubusercontent.com/1172204/45295469-16fade80-b4ff-11e8-8367-a8f80718f220.png)

I now it used to work, but I am not able to figure out, what is missing.

I am using the latest released version of django-SHOP.

**Comment by jrief** [comment]
Please upgrade to djangocms-bootstrap3 version 0.4.2 and try again.
Also note that, you now can use the latest version of angular-ui-bootstrap, ie. version 2.5.6

**Comment by jrief** [comment]
@markusmo does this fix your problem?

**Comment by markusmo** [comment]
Yeah, tried it out. Works great.

----------------
Markus Mohanty MSc.
Tel.: 06763239108

Jacob Rief <notifications@github.com> schrieb am Mo., 10. Sep. 2018, 23:54:
