### ISSUE TITLE
Improperly configured error

### ISSUE THREAD

**Issue by calvinkcc** [awesto/django-shop#750]
So I have tried windows, Linux and ever a production server. Every time I tried all the steps and when I try to migrate this error pops up.
"raise ImproperlyConfigured("Environment variable DJANGO_SHOP_TUTORIAL is not set")
django.core.exceptions.ImproperlyConfigured: Environment variable DJANGO_SHOP_TUTORIAL is not set
"
I can assure that I have export the DJANGO_SHOP_TUTORIAL as commodity and DJANGO_DEBUG=1
I also checked the env using "env" command and also checked export using "export" command. Both of them displays the env properly.
Please send help.

**Comment by jrief** [comment]
This happens in line 29 of ``settings.py``. If you read the preceding code, you see that this environment variable simply isn't set. I can't tell you anything else.

**Comment by calvinkcc** [comment]
Jesus, I'm dumb. So we cannot leave it as an array and have to choose one of them matching to our environment variable. I thought differently. Thanks.

**Comment by mdnur89** [comment]
@calvinkcc hey man, I'm apparently encountering the same problem as I'm running it for the second time and I want to run another demo the i18n polymorphic. Is it that I must actually edit the settings.py manually inputting the SHOP_TUTORIAL=i18n_polymorphic
DEBUG=1.
?
Sorry for the inconvenience, I need help.

**Comment by jrief** [comment]
use environment variables
