### ISSUE TITLE
File is not a zip file

### ISSUE THREAD

**Issue by calvinkcc** [awesto/django-shop#751]
Hello

"File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file"

I searched the closed issues, someone else had this error and apparently fixing the broken link by the upload fixed the issue. 

Thanks for your time.

**Comment by jrief** [comment]
Please provide a reproducible error report.
