### ISSUE TITLE
How can i add my own app and urls in django-shop?

### ISSUE THREAD

**Issue by Richardhongyu** [awesto/django-shop#762]
I have run 'startapp' successfully,and i add some urls in the urls.py of my app;
But when i try to get my new site in chrome ,it doesn't work.
Am i supposed to run something else to make my change accepted by django-shop?
Thanks for your time!

**Comment by Richardhongyu** [comment]
I noticed that uwsgi is running in one of my docker containers.
Does it means that if i make some changes ,it will be saved autoly.

**Comment by jrief** [comment]
what do you mean by
> I have run 'startapp' successfully

The best approach is to start using https://github.com/awesto/cookiecutter-django-shop and then evolve into a shop with product models describing the models you want to sell.

**Comment by Richardhongyu** [comment]
I need to add some functions now，which are more than selling products. So I execute the code './manage.py startapp myapp name'. How can I make my changes saved?

**Comment by jrief** [comment]
Please use the issue tracker to ask questions related to django-SHOP.
