### ISSUE TITLE
Field `OrderItem.quantity` must be of same type as `CartItem.quantity`

### ISSUE THREAD

**Issue by stilet** [awesto/django-shop#766]
when starting django pipenv :

```
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:
ERRORS:
?: Field `OrderItem.quantity` must be of same type as `CartItem.quantity`.
```

**Comment by jrief** [comment]
Seems that you are mixing the merchant implementation created by cookiecutter-django-shop for version 1.1 with django-shop version 1.0. The Pipfile in your merchant implementation wants https://github.com/awesto/django-shop/archive/releases/1.1.x.zip , so please recheck.

**Comment by jrief** [comment]
Please note that in version 1.1 the default `CartItem.quantity`changed from `IntegerField` to `PositiveIntegerField`. So just fix your `OrderItem.quantity` to the same type.

**Comment by jrief** [comment]
Sorry @stilet , this change was scheduled for version 1.1, but unfortunately slipped into version 1.0.1. If you want I can create a fix and release that as 1.0.2, however in 1.1 is changes again.

**Comment by stilet** [comment]
Thanks it's not urgent :+1:   - I'm just starting to deal with django-shop

**Comment by jrief** [comment]
In version 1.0.2 it has been fixed.
