### ISSUE TITLE
Error in function validate_quantity

### ISSUE THREAD

**Issue by stilet** [awesto/django-shop#767]
In version 1.0.2, an error in  function validate_quantity  in shop/serializers/defaults/catalog.py.
Manifested when working with products with several options.
Need to remove the field availability

```
def validate_quantity(self, quantity):
        """
        Restrict the quantity allowed putting into the cart to the available quantity in stock.
        """
        # availability = self.instance['availability']
        # return min(quantity, availability.quantity)
        # FIXME 
        return quantity
```

**Comment by jrief** [comment]
Can you please send me a stack-trace using a service such as https://dpaste.de
Between version 1.0 and 1.1 stock management was refactored. I'm afraid that some code from version 1.1 slipped into 1.0.2.
Can you please retry using the next upcoming version 1.1. Currently only available from GitHub, not PyPI.

**Comment by jrief** [comment]
django-shop version 1.0.2 downloaded from PyPI in `shop/serializers/defaults/catalog.py` there is no method `validate_quantity(...)`. Can it be that you started to use version 1.1 from GitHub?

**Comment by stilet** [comment]
sorry, somehow I had version 1.1 dev
