### ISSUE TITLE
Error while issuing  initialize_shop_demo command

### ISSUE THREAD

**Issue by beeduino** [awesto/django-shop#770]
I am getting an error during demo shop initialize.
./manage.py initialize_shop_demo throws:
...
  File "/usr/lib/python3.5/zipfile.py", line 1026, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.5/zipfile.py", line 1094, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

It seems that the file to be downloaded 
http://downloads.django-shop.org/django-shop-workdir-17.zip is not accessible.
What could be done to resolve this?

**Comment by jrief** [comment]
Thanks for reporting.
There was a problem with the configuration of the webserver.
Please change the download URL to https, or recreate the project with the latest cookiecutter version.
