### ISSUE TITLE
Cookie Cutter Version ignores PostalShippingModifier

### ISSUE THREAD

**Issue by moellering** [awesto/django-shop#772]
I'm using the cookie cutter version from the [tutorial of the documentation](https://django-shop.readthedocs.io/en/latest/) as an example for my own implementation. 

Shipping modifiers that should add a line to the cart are ignored in both variants  as soon as their activation is dependent on the selection in the shipping form.
If there is only one shipping modifier is present the line is added though.

Using the debugger shows that self.is_active(cart) always returns False.

The image shows the resulting order. Note the selection of "postal shipping" and the lack of 5 € shipping costs.

![image](https://user-images.githubusercontent.com/2493235/63439764-f5081c80-c42e-11e9-84b6-2b0a7198d599.png)

Code of the modifiers.py that is generated by cookie cutter:

```
class PostalShippingModifier(ShippingModifier):
    identifier = 'postal-shipping'

    def get_choice(self):
        return (self.identifier, _("Postal shipping"))

    def add_extra_cart_row(self, cart, request):
        if not self.is_active(cart) and len(cart_modifiers_pool.get_shipping_modifiers()) > 1:
            return
        # add a shipping flat fee
        amount = Money('5')
        instance = {'label': _("Shipping costs"), 'amount': amount}
        cart.extra_rows[self.identifier] = ExtraCartRow(instance)
        cart.total += amount

    def ship_the_goods(self, delivery):
        if not delivery.shipping_id:
            raise ValidationError("Please provide a valid Shipping ID")
        super(PostalShippingModifier, self).ship_the_goods(delivery)

```

**Comment by moellering** [comment]
I think, the cookie cutter version produces a modifiers.py which does not work with the django-shop version.
After replacing `self.is_active(cart)` by `self.is_active(cart.extra.get("shipping_modifier",None))` the shipping costs are displayed and calculated properly.

**Comment by jrief** [comment]
@moellering Thanks for reporting.
This indeed is a bug and has been fixed.
Please report bugs related to cookiecutter-django-shop at the proper project on GitHub.
