### ISSUE TITLE
from django.utils.text import force_text ImportError: cannot import name 'force_text'

### ISSUE THREAD

**Issue by azzerilla** [awesto/django-shop#777]
Hi, I'm new to the Django-shop.
when I try to run django-shop cookiecutter I get this error:
in django-shop/shop/models/fields.py
from django.utils.text import force_text
ImportError: cannot import name 'force_text'
I found that force_text has imported from django.utils.encoding in other modules.

Django version: 2.2.6
Django-CMS version: 3.7.0
Django-Shop version 1.0.2

**Comment by jrief** [comment]
The current version of django-SHOP, only supports Django up to version 1.11.
The next version, will add support up to Django-2.2. You can have a preview from https://github.com/awesto/django-shop/tree/releases/1.1.x
I hope, I will be able to release version 1.1 at the beginning of November.

**Comment by azzerilla** [comment]
thank you @jrief :)
