### ISSUE TITLE
Customize Registration from

### ISSUE THREAD

**Issue by azzerilla** [awesto/django-shop#783]
Hi

I want to customize the registration form to be able to get the first_name and last_name in the form.
what's the best solution for doing this?

**Comment by haricot** [comment]
I started to implement in the  WIP django2 #776 , the starting point is to modify this:
https://github.com/awesto/django-shop/blob/5160815f5af1724495092410a1bac66cd622cab9/shop/cascade/auth.py#L23

**Comment by azzerilla** [comment]
Thank you @haricot
