### ISSUE TITLE
Product with subscription period

### ISSUE THREAD

**Issue by azzerilla** [awesto/django-shop#784]
Hi

would you please tell if there is any functionality for defining products that have a subscription period?
what is the best way to make it done? just customizing the Product model is fine or there is any better way?

**Comment by jrief** [comment]
Here the best approach is to leave this to the merchant's implementation. There are so many different subscription models, that it just doesn't make sense to implement them in a generic manner.

I actually implemented a product type with subscription for a client using django-SHOP. Don't hesitate to contact me on my private email address, if you need consultation on this.

**Comment by azzerilla** [comment]
dear @jrief  thank you very much :)
