### ISSUE TITLE
bsp-scrollpanel.tmpl.html Not Found

### ISSUE THREAD

**Issue by markusmo** [awesto/django-shop#800]
Hi
I am playing around with the latest released version. I used the cookiecutter, i18n, not polymorphic.
And when I tried to implement my own product page I got a wierd error:
`[2020-04-04 21:10:57,072 basehttp] WARNING: "GET /de/catalog/scrollpanel/bsp-scrollpanel.tmpl.html HTTP/1.1" 404`
The browser is telling me:
`Error: "[$templateRequest:tpload] Failed to load template: scrollpanel/bsp-scrollpanel.tmpl.html (HTTP status: 404 Not Found)
https://errors.angularjs.org/1.7.9/$templateRequest/tpload?p0=scrollpanel%2Fbsp-scrollpanel.tmpl.html&p1=404&p2=Not%20Found"
    Angular 9
angular.min.js:15570:41
`
I quite don't get the problem, as I did not change die urls.py file and I also imported all templatetags and scripts neccessary. I tried collectstatic, but it also did not help... 

Do you have any suggestion where I have to look? I am running out of ideas.

**Comment by jrief** [comment]
Good question.
This template is not loaded through a HTTP GET request, instead it must be defined through a `<script type="text/ng-template">` tag. See here for details: https://docs.angularjs.org/api/ng/directive/script
It then is used by the directive `bspScrollpanel` which can be found in [angular-bootstrap-plus](https://github.com/jrief/angular-bootstrap-plus).

**Comment by markusmo** [comment]
Okay. I included the template and everything was fine.
In the end I added `{% include "shop/catalog/bsp-scrollpanel.tmpl.html" %}` to my template and it worked like a charm!
