### ISSUE TITLE
Checkout form, sending my order

### ISSUE THREAD

**Issue by markusmo** [awesto/django-shop#806]
I am logged in as a customer and I am checking out my cart, but at step 4, the last step, the proceed button which should create an order and so forth will not let me purchase my order.

So I am quite confused, as there is no exception and I also did not change that particular part of the ordering process.

**Comment by jrief** [comment]
Is there any error logged in the browser console? The purchase button interacts with JavaScript.

**Comment by markusmo** [comment]
Sadly not. There are no JS errors or errors when sending HTTP-Requests:
<img width="588" alt="requests" src="https://user-images.githubusercontent.com/1172204/79690396-7d5aed80-825a-11ea-8c0e-7ad67a2071e8.png">
Also there are no errors on webserver side.

**Comment by haricot** [comment]
If it helps:
With poetry.lock: django-shop==1.2 and django-rest-framework==3.9.3 and drf-haystack==1.8.6:
Step 4 is passed: with 'Pay in advance' and 'Postal shipping', i can see the  button "purchace now" and if i click, I can see the view "thank you for your order"

**Comment by markusmo** [comment]
I just checked my dependencies and my only difference is that I have djangorestframework==3.10.3
I also updated my django-shop to 1.1.3 but that did not change a thing.

**Comment by markusmo** [comment]
Ok, I reinstalled all my dependencies and I managed to get it working.
