### ISSUE TITLE
Product gallery product not JSON serializable

### ISSUE THREAD

**Issue by markusmo** [awesto/django-shop#808]
I tried to add the CMS plugin for Product Gallery into my layout.
After being able to select my products, while pressing the save button I got following error message: https://gist.github.com/markusmo/4be685a83fe6c53d025b3af39c445f9b

I have checked my serializer for my products and in the Catalog-App it is working just fine.

**Comment by jrief** [comment]
Has been fixed in version 1.2. Will backport to version 1.1. Thanks for reporting.
