### ISSUE TITLE
How do I correctly configure my Product Catalog?

### ISSUE THREAD

**Issue by markusmo** [awesto/django-shop#809]
I am a bit confused.
I am configuring my Catalog with CMS. I have my root object, and then my sub pages. All of them have "Catalog List" selected as their "Application". But in my Catalog, I always see all the products, there are no filters applied ... I also see no errors, this is a bit confusing for me.

**Comment by markusmo** [comment]
When I add or change the cms I get `site-packages/cms/plugin_base.py:286: DontUsePageAttributeWarning: Don't use the page attribute on CMSPlugins! CMSPlugins are not guaranteed to have a page associated with them!
  page=obj.page`

And as I have a look at my categories the `CatalogList` still does not filter my products to their assigned CMSPages. Could it be, that this warning is indicating, that my CMSPages are not working properly?

**Comment by jrief** [comment]
You should only add the "Catalog List" as CMSApp to pages, which actually need to render a list view of products. This also handles the routing of the product's detail view.

> Could it be, that this warning is indicating, that my CMSPages are not working properly?

No, that warning originates from the CMS itself. If a plugin isn't associated with a page, for example in the clipboard, then the `obj.page` attribute is `None`. There is nothing special about this.

**Comment by markusmo** [comment]
So that I get it right: I have a "catalog" CMS-page, which is configured as a "Catalog List" and my categories, which are sub-CMS-pages also have to have "Catalog List".
Then my product, which should be displayed in my "catalog" and my category does have both CMS-pages assigned in their configuration?
When I configure it that way, I always get all products in my "catalog" and my subcategory

**Comment by jrief** [comment]
<img width="849" alt="Screenshot 2020-06-17 at 22 49 31" src="https://user-images.githubusercontent.com/1132472/84949126-083a5600-b0ed-11ea-933e-c4817242e242.png">
all four "categories" (Catalog, Smart Cards, Earphones, Smartphones) which actually are CMS-pages) have the "Catalog List" app assigned to them.
<img width="647" alt="Screenshot 2020-06-17 at 22 52 47" src="https://user-images.githubusercontent.com/1132472/84949428-839c0780-b0ed-11ea-94e9-bd9879523756.png">
Then we can assign each product to one or more of those categories / CMS-pages:
<img width="858" alt="Screenshot 2020-06-17 at 22 57 20" src="https://user-images.githubusercontent.com/1132472/84949708-ee4d4300-b0ed-11ea-8a2b-238fd0fbc184.png">

**Comment by markusmo** [comment]
Thanks :-)
