### ISSUE TITLE
 How to extend iso4217.py from outside the application?

### ISSUE THREAD

**Issue by jhonvidal** [awesto/django-shop#816]
How to extend iso4217.py from outside the application?

I want to create my own currency that is not found in iso4217.py

my custom currency_code not in CURRENCIES and therefore I get an error.

please help.

**Comment by jrief** [comment]
At the end of `iso4217.py`, I added 
>  # feel free to add more currencies, alphabetically ordered

so, please add your currency, create a pull request and I will merge it immediatly.

**Comment by jhonvidal** [comment]
Thanks for answering.
My question is to know if there is a possibility to add new currencies externally without affecting the core of the project.

Anyway I just sent a pull request.

Thank you so much!

**Comment by jrief** [comment]
or just tell me, which currency you need.

**Comment by jhonvidal** [comment]
I have sent pull request

**Comment by jrief** [comment]
closed via #818
