### ISSUE TITLE
How to implement crowdfunding?

### ISSUE THREAD

**Issue by adnanmuttaleb** [awesto/django-shop#817]
In my app, instead of product there is a project, each project has a target goal e.g 1000$, where each user can donate 5$, 10$ ..etc. Also each project similarly to a product belong to a category, e.g health, education..etc. How model this? and is it possible?

**Comment by jrief** [comment]
You mean something like Kickstarter?

I usually use CMS pages to organize categories. You then just have to assign the products to these pages. There you can create list views and add all other sorts of additional information.

The product model to create such an application should be quite simple. I would use the `Commodity` as a blueprint and start from there. It allows you to use all plugins from django-CMS to create nice pages.

To this model, you then can add a target goal and a reached goal. Each time someone donates via checkout, the reached goal is incremented by that amount.
