### ISSUE TITLE
pipenv run ./manage.py initialize_shop_demo [ERROR]

### ISSUE THREAD

**Issue by HamzaOPLEX** [awesto/django-shop#867]
Hello,
when i try to run this command :
`pipenv run ./manage.py initialize_shop_demo`
i get this error 

[home/theoplex/.local/share/virtualenvs/oplexshop-g6RNzT8i/lib/python3.8/site-packages/shop/apps.py:32: UserWarning: 
Your caching backend does not support invalidation by key pattern.
Please use "django-redis-cache", or wait until the product's HTML
snippet cache expires by itself.
  warnings.warn("\n"
SystemCheckError: System check identified some issues:

ERRORS:
<class 'filer.admin.folderadmin.FolderAdmin'>: (admin.E039) An admin for model "User" has to be registered to be referenced by FolderAdmin.autocomplete_fields.
<class 'filer.admin.permissionadmin.PermissionAdmin'>: (admin.E039) An admin for model "User" has to be registered to be referenced by PermissionAdmin.autocomplete_fields.]

i am using : 
 - ubuntu 20.04
 - python 3.8

**Comment by chandave** [comment]
Are you using a version of django-filer newer than 2.0.2? If you are then you need to down-grade to v2.0.2.

Check Issue #845 for more details.

**Comment by HamzaOPLEX** [comment]
thank you issue resolved after installing django-filter==2.0.2
`pipenv install  django-filer==2.0.2`
