### ISSUE TITLE
Django 3.2

### ISSUE THREAD

**Issue by Josephine-Marie** [awesto/django-shop#871]
Hello, I have seen that the LTS for Django 2.2 comes to an end in 2 months so my question is: 

Will Django-SHOP be made compatible for Django 3.2 on time?

**Comment by jrief** [comment]
It is already compatible with Django-3.2. However, I haven't had enough time to bundle a new release. It takes a lot of time to test everything, therefore I waited. Sorry for that.

**Comment by Josephine-Marie** [comment]
no thats great! thanks for letting me know
